### ISSUE TITLE
[Bug]: Compromise library not working in development anymore

### ISSUE THREAD

**Issue by skovhus** [rolldown/rolldown#5847]
### Reproduction link or steps

https://stackblitz.com/edit/github-z3jerszh-yzc4e3uh?file=package.json,src%2Fmain.ts

### What is expected?

Development should work like production. Regressed fairly recently. Broken in 7.1.2, worked in 7.0.12

### What is actually happening?

It crashes in development, maybe due to some local scope issues?

```
Uncaught TypeError: nlp$1.addTags is not a function
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
```

**Comment by IWANABETHATGUY** [comment]
I can't reproduce it with `pnpm dev` or `pnpm build && pnpm preview`

**Comment by skovhus** [comment]
I might have copied a link to an old version of the stackblitz link, I just updated it. 

`pnpm dev` renders an empty white screen, `pnpm build && pnpm preview` renders `Works and did not crash if you see this`

**Comment by IWANABETHATGUY** [comment]
seems related to https://github.com/rolldown/rolldown/pull/5764
