### ISSUE TITLE
[Bug]: Minifier bug since beta.59

### ISSUE THREAD

**Issue by lazka** [rolldown/rolldown#7848]
### Reproduction link or steps

reduced example:

```js
var require_pdfAnnotate = function() {
  return {
    function() { eval() }
  }
}
function n() {}
n.d = (y, x) => {
  for (var z in x)
    n.o()
}, n.o = () => 0
var r
n.d(r, {hT : () => C})
```

which is minified to (using `rolldown index.js --file broken.js --minify`):

```js
var require_pdfAnnotate = function () {
  return {
    function() {
      eval();
    },
  };
};
function n() {}
((n.d = (e, t) => {
  for (var n in t) n.o();
}),
  (n.o = () => 0));
var r;
n.d(r, { hT: () => C });
```

### What is expected?

```
$ nodejs index.js
```

### What is actually happening?

After minify I get:

```
$ nodejs broken.js
TypeError: n.o is not a function
```

### System Info

```Shell
rolldown --version
rolldown v1.0.0-beta.59
```

### Any additional comments?

It works with rolldown v1.0.0-beta.58

**Comment by camc314** [comment]
I broke this in oxc with the mangler change, will fix.

**Comment by sapphi-red** [comment]
Probably related to https://github.com/rolldown/rolldown/issues/7843 and https://github.com/oxc-project/oxc/issues/17956
