### ISSUE TITLE
[Bug]: builtin wasm fallback fails on wasm-bindgen ESM `import * as wasm from "*.wasm"`

### ISSUE THREAD

**Issue by stanislav-ctrl** [rolldown/rolldown#9859]
### Reproduction link or steps

1. Create a vanilla **Vite 8** app (Rolldown is the bundler — no extra setup).
2. Depend on any `wasm-bindgen --target bundler` package — e.g. `@cedar-policy/cedar-wasm@4.11.1`. Its ESM entry contains the problematic import:
   ```js
   // node_modules/@cedar-policy/cedar-wasm/esm/cedar_wasm.js
   import * as wasm from "./cedar_wasm_bg.wasm";
   ```
3. Import the package from app code (and, to also exercise the worker path, from a `*.worker?worker`).
4. Run a plain **`vite build`**.

### What is expected?

Rolldown bundles the `*.wasm` import natively — the builtin fallback emits the `.wasm` as an asset and instantiates it — exactly as rollup-Vite does with `vite-plugin-wasm`.

### What is actually happening?

`vite build` fails because the builtin fallback throws on the `.wasm` import (here it surfaces in both the app graph and the worker via `[plugin vite:worker]`):

```text
Build failed with 2 errors:
node_modules/@cedar-policy/cedar-wasm/esm/cedar_wasm_bg.wasm
╭─[ node_modules/@cedar-policy/cedar-wasm/esm/cedar_wasm.js:3:23 ]
3 │ import * as wasm from "./cedar_wasm_bg.wasm";
`builtin:vite-wasm-fallback` threw an error
  [plugin vite:worker]
  at aggregateBindingErrorsIntoJsError (…/rolldown/dist/shared/error-*.mjs)
```

### System Info

```Shell
System:
    OS: macOS 26.5.1
    CPU: (12) arm64 Apple M4 Pro
    Memory: 342.44 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.12.0 - /Users/stanislavt/.nvm/versions/node/v24.12.0/bin/node
    Yarn: 4.12.0 - /Users/stanislavt/.nvm/versions/node/v24.12.0/bin/yarn
    npm: 11.6.2 - /Users/stanislavt/.nvm/versions/node/v24.12.0/bin/npm
  Browsers:
    Chrome: 149.0.7827.116
    Firefox: 151.0.3
    Safari: 26.5
```

## Summary

When building a Vite 8 project (which uses Rolldown as its bundler — `vite@8` depends on `rolldown` directly), importing a third-party WebAssembly library compiled with `wasm-bindgen --target bundler` causes a fatal `vite build` error.

Rolldown's builtin WASM handler (`builtin:vite-wasm-fallback`) intercepts the generated `import * as wasm from "./*_bg.wasm"` statement but throws without an actionable message — it appears unable to process that import form.

On rollup-based Vite this case is handled by `@rollup/plugin-wasm` / `vite-plugin-wasm`. Under Rolldown those don't help (see _Attempted workarounds_ below), so this looks like a gap in Rolldown's builtin WASM support for standard `--target bundler` packages.

## Attempted workarounds (neither resolves it)

- **`vite-plugin-wasm`** — loads fine but does **not** change the outcome; the builtin `vite-wasm-fallback` still throws.
- **`vite-plugin-top-level-await`** — can't even be loaded: it hard-depends on `require("rollup")`, which isn't present under Rolldown:
  ```text
  Failed to load preset: Error: Cannot find module 'rollup'
    at … vite-plugin-top-level-await/dist/index.js:41
  ```
## Possibly related

PR #9775 ("refactor(rolldown_plugin_vite_wasm_fallback): remove the plugin") was merged 2026-06-15 — i.e. **after** the latest release (1.1.1, published 2026-06-11), so it isn't in any published build yet. Does that change remove/replace the fallback that's throwing here, and which release will include it?

## Questions for maintainers

1. Should Rolldown's builtin fallback handle this `--target bundler` import form natively?
2. If a Rolldown-native WASM plugin is the expected route instead, which one?
3. Could the builtin fallback emit a clearer error (pointing to the right approach) instead of failing opaquely?

If this is a known limitation of the in-progress WASM handling (e.g. pending #9775) rather than a regression, happy to have it reframed as an enhancement.

**Comment by IWANABETHATGUY** [comment]
@shulaoda could you have a look?

**Comment by Christoph-Wagner** [comment]
I was just hit by this on 1.1.2, downgrading back to 1.1.1 fixes it. The Vite version fixing this (via https://github.com/vitejs/vite/pull/21779) has not yet been published. 1.1.2 works with Vite 8.1.0-beta.0, but Vite 8.0.16 requires 1.1.1

**Comment by shulaoda** [comment]
Thanks for reporting this issue, I think it has been resolved in the latest `vite@8.1.0` version.
