### ISSUE TITLE
[Bug]: Inlining dynamic imports broken with multiple entry points (beta.59 regression)

### ISSUE THREAD

**Issue by lazka** [rolldown/rolldown#8027]
### Reproduction link or steps

https://repl.rolldown.rs/#eNptj81uhCAUhV/lhg2aWDqzdTJ9hSZNd6ULo1hp9GIA+xPCuxdE7ExmEhbcn/Odcx3pSe2IVuPYqW9krcJefjBrYhdJfW9SkTYM5DQrbcH+zgIcvGxrz7OVCg146LWagGY55cgxIIyFBKpvJGdwHAEkzout4Y1OjUT2aWhFlR2Ejt/3iqOPJPGzmneib5YxIzkSX5G8nA/Y66vYnLBHMzRadGHEySkq9zpL/xtJu7n2C7Yx8vopyhQbQAu7aAT6OkgD4TWQ9Ps+Pa3po9V2WzbK5WXEgl4kpCULZ2BRuJUGvoTzUzZOMSK8DHcE+leAHNmBHR50y47E/wF/s6Ha

### What is expected?

The dynamic import works as expected.

### What is actually happening?

The dynamic import imports a module that doesn't have any exports after bundling.

```js
dist/main.js:3
	func();
	^

TypeError: func is not a function
    at dist/main.js:3:2
```

### System Info

```Shell
rolldown: 1.0.0-rc.1
```

### Any additional comments?

I suspect this is caused by #7742

**Comment by lazka** [comment]
Thanks!

**Comment by lazka** [comment]
Now (with rc2) the dynamic import works, but my static import imports "undefined" in my app. I need to find a new reproducer.

**Comment by pioug** [comment]
I think I am facing the same issue as you in 1.0.0-rc.2, it seems related to helper functions inserted by Rolldown.

```
D2Br6HHU.js:4 Uncaught TypeError: __exportAll is not a function
    at D2Br6HHU.js:4:39
```

I can't reproduce this in the REPL but here are more details about my case. I have a module imported both statically and dynamically and that seems to confuse the bundler as it creates circular dependencies.

| # | Description | Screenshot |
|---|------------|------------|
| 1 | Chunk A defines and exports `__exportAll` | <img width="212" height="78" alt="Chunk A defines and exports __exportAll" src="https://github.com/user-attachments/assets/7ebc849c-47ec-4784-bd71-1fabc904a1ae" /> |
| 2 | Chunk A also imports chunk B | <img width="1062" height="59" alt="Chunk A imports chunk B which needs __exportAll" src="https://github.com/user-attachments/assets/701a0d31-6738-4be6-bac3-8a7c26fd6208" /> |
| 3 | `__exportAll` is undefined in chunk B | <img width="407" height="94" alt="__exportAll is undefined in chunk B" src="https://github.com/user-attachments/assets/a5186e2d-bb7c-40cf-bdc4-ab973cd26397" /> |

Disabling `chunkOptimiszation` (https://rolldown.rs/reference/Interface.RolldownOptions#chunkoptimization) fixes it for me.

**Comment by IWANABETHATGUY** [comment]
> I think I am facing the same issue as you in 1.0.0-rc.2, it seems related to helper functions inserted by Rolldown.
> 
> ```
> D2Br6HHU.js:4 Uncaught TypeError: __exportAll is not a function
>     at D2Br6HHU.js:4:39
> ```
> 
> I can't reproduce this in the REPL but here are more details about my case. I have a module imported both statically and dynamically and that seems to confuse the bundler as it creates circular dependencies.
> 
> #	Description	Screenshot
> 1	Chunk A defines and exports `__exportAll`	<img alt="Chunk A defines and exports __exportAll" width="212" height="78" src="https://private-user-images.githubusercontent.com/3654180/543182302-7ebc849c-47ec-4784-bd71-1fabc904a1ae.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk4NDU5MzAsIm5iZiI6MTc2OTg0NTYzMCwicGF0aCI6Ii8zNjU0MTgwLzU0MzE4MjMwMi03ZWJjODQ5Yy00N2VjLTQ3ODQtYmQ3MS0xZmFiYzkwNGExYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAxMzFUMDc0NzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmZkZDNiZjNmOGUwYjMyMTM0ZjBkZGRjYjU2MjJkNmJjMzM2ZGI4MjZiYzNjNTNiMDVhMTJhNDRhM2U4NGU0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Jxj6_6VCHg-V7nE7oKnXnux4TmUcqv2NDIWRP-LqR0c">
> 2	Chunk A also imports chunk B	<img alt="Chunk A imports chunk B which needs __exportAll" width="1062" height="59" src="https://private-user-images.githubusercontent.com/3654180/543182235-701a0d31-6738-4be6-bac3-8a7c26fd6208.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk4NDU5MzAsIm5iZiI6MTc2OTg0NTYzMCwicGF0aCI6Ii8zNjU0MTgwLzU0MzE4MjIzNS03MDFhMGQzMS02NzM4LTRiZTYtYmFjMy04YTdjMjZmZDYyMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAxMzFUMDc0NzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjEzMDc1Mzg3ZDcyMzdlNGE2MmEzMWIyNmM4ZmFiZmQxZTAxNGIzMjVhYmQ5MTNmYjA4MzJlOTc1MzBlNTA4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cQm16imCxYCpS3yfsHvER1FlTXBqwdwdF4MBrLe5AUI">
> 3	`__exportAll` is undefined in chunk B	<img alt="__exportAll is undefined in chunk B" width="407" height="94" src="https://private-user-images.githubusercontent.com/3654180/543181960-a5186e2d-bb7c-40cf-bdc4-ab973cd26397.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk4NDU5MzAsIm5iZiI6MTc2OTg0NTYzMCwicGF0aCI6Ii8zNjU0MTgwLzU0MzE4MTk2MC1hNTE4NmUyZC1iYjdjLTQwY2YtYmRjNC1hYjk3M2NkMjYzOTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAxMzFUMDc0NzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTE4OTRmYzI4ZjE4NGFiODMwMGNiZDM0OGMwMTU2Y2IzNmViNDI1NWU0Y2IzM2NlNTUzYWY4MTc5NTExZDczMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.EYvrvSTlTuMpAILEsa53rUBF_xqokzvcVSGpo2lScmg">
> Disabling `chunkOptimiszation` (https://rolldown.rs/reference/Interface.RolldownOptions#chunkoptimization) fixes it for me.

It seems there is still a possibility of generating a circular reference when optimizing chunk generation. I will have a look.

**Comment by lazka** [comment]
I haven't had time to investigate further, but I can confirm that disabling `chunkOptimization` makes things work again, using rc2. thanks @pioug

**Comment by lazka** [comment]
I've created a reproducer of the new issue in #8184

It was tricky to reduce, so there are quite a few files, but only a few lines in total at least.
