### ISSUE TITLE
[Bug]: circular import generated when using dynamic import and require

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#9597]
### Reproduction link or steps

[REPL](https://repl.rolldown.rs/#eNqNkk1v2zAMhv8KodMGxI4/hrTzsGMw7LTDdpsHV7FpV50qpZLsJg3y36sPx3WKFAhgGCZFvnz4ygfSkuJAhGwwiesH7QNSzBILUtu443JD+Z97puOqovW+5qyuZG+2vana/uWlSuA7JN9KMUjWgMKnnin8VJJ46ZTy+EGX5LM9xt1WKqNjl5167AwkhVE9Hhd+cmrr5yQ+vhIktaLpCYQ9unETh98ogAxUgYdw9YejzYQoHijvcdQItHA4VboyMjJm7+0KiSspMzsh+8iuGeaZX6emE4KzdU7g4ysBcquVf2CTs3t06cKp3/OdiU7tzcR8MtFNODcxn0xUkvNGPou4lqJl3WyXCydhq+USfqBARQ02sNnDXU1VJ0H1AqItXFgTomjDBHRjU9WynekV2rR9NFqV2+wmS5Ms+7L6mmar9CZf3d5NzA22tOeWvRQATFjVInwDlASFUfsoKUlhg7OLcxXHhXvjzqASlBfw1zaMgev554+NQtT39D8W0FKu0Se3CjWqAddO/zfrBHXI2k2hnMvnyOkIzaQoiW8I+05k2ihWm/UO697Yol+qQTXXB3hkgrX7nyLgrMMvNi9x8OGa7D0N1nhuzdOGHF8BDZ9o+Q==)

### What is expected?

No error happens when executing `dist/entry-0.js`.

### What is actually happening?

The following error happens when executing `dist/entry-0.js`:
```
TypeError: __exportAll is not a function
```
In other words, the cyclic import "entry-0 -> node0 -> entry-0" is not output.

### System Info

```Shell
REPL 1.0.3
```

### Any additional comments?

This seemed to be working with 1.0.0.
Found at https://github.com/sapphi-red/zarara/issues/25#issuecomment-4560201943
