### ISSUE TITLE
strictExecutionOrder: pre-chunk consumer-local barrel routing without matching lowering emits a startup-crashing CJS chunk cycle

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#10515]
### Summary

With `strictExecutionOrder`, the pre-chunk consumer-local barrel probe can make a routing decision that final lowering never materializes. Chunk placement then splits a CJS re-export barrel's leaves per consumer while the emitted barrel keeps its monolithic interop wrapper, producing chunks that `require()` each other in a cycle. Loading either entry crashes at startup:

```
TypeError: require_barrel.init_barrel is not a function
```

Regression introduced by #10488 (part of the #10294 strict-order work). Bisected to exactly that merge:

| Commit | Result |
| --- | --- |
| `f5a53205e` (main, merge parent) | pass |
| `9fef0099f` (main, squash-merge of #10488) | **crash** |

Both wrap-all and `experimental.onDemandWrapping` are affected.

### Reproduction

Seven one/two-line modules. Two CJS entries each `require()` their own ESM forwarder into one shared re-export-only barrel over two CJS leaves; output format `cjs`:

```js
// entry-a.cjs
const { a } = require('./forwarder-a.mjs');
module.exports = { a };

// entry-b.cjs
const { b } = require('./forwarder-b.mjs');
module.exports = { b };

// forwarder-a.mjs
export { a } from './barrel.js';

// forwarder-b.mjs
export { b } from './barrel.js';

// barrel.js
export { a } from './a.cjs';
export { b } from './b.cjs';

// a.cjs
exports.a = 'a';

// b.cjs
exports.b = 'b';
```

Options: `input: [entry-a.cjs, entry-b.cjs]`, `format: 'cjs'`, strict execution order enabled (no other non-default options; no `sideEffects` annotations needed).

As a rolldown Rust fixture (validated form), drop the files above plus this `_config.json` and `_test.mjs` into `crates/rolldown/tests/rolldown/function/experimental/strict_execution_order/cjs_reexport_barrel_probe_plan_divergence/` and run `cargo test -p rolldown --test integration probe_plan_divergence`:

```json
{
  "configName": "wrap-all",
  "config": {
    "input": [
      { "name": "entry-a", "import": "./entry-a.cjs" },
      { "name": "entry-b", "import": "./entry-b.cjs" }
    ],
    "strictExecutionOrder": true,
    "format": "cjs"
  },
  "configVariants": [{ "_configName": "on-demand", "onDemandWrapping": true }]
}
```

```js
// _test.mjs
import assert from 'node:assert';

const entryA = await import('./dist/entry-a.js');
assert.strictEqual(entryA.a, 'a');

const entryB = await import('./dist/entry-b.js');
assert.strictEqual(entryB.b, 'b');
```

### Observed output

The barrel chunk keeps the monolithic interop wrapper but its leaves were placed into the two entry chunks, so every chunk requires the others:

```js
// dist/barrel.js
const require_rolldown_runtime = require("./rolldown-runtime.js");
const require_entry_a = require("./entry-a.js");
const require_entry_b = require("./entry-b.js");
var import_a, import_b;
var init_barrel = require_rolldown_runtime.__esmMin((() => {
	import_a = require_entry_a.require_a();
	import_b = require_entry_b.require_b();
}));
```

`entry-a.js` hosts `require_a` (and requires `barrel.js`), `entry-b.js` hosts `require_b`. Requiring `entry-a.js` therefore loads `barrel.js`, which loads `entry-b.js`, whose body calls `require_barrel.init_barrel()` while `barrel.js` is still mid-load — `init_barrel` is not exported yet, so it throws. Loading one entry also executes the other entry's module body along the way.

On `f5a53205e` both leaves are placed in the shared barrel chunk and both entries load correctly.

### Mechanism

- `generate_chunks` builds a pre-chunk probe (`pre_chunk_order_state`) that runs `consumer_local_reexport_plan` unconditionally and routes entry reachability per consumer (`determine_reachable_modules_for_entry`), so `a.cjs` gets only entry-a's bit and `b.cjs` only entry-b's.
- In this graph every reachable ESM module is already `WrapKind::Esm` (the CJS entries `require()` the forwarders, interop-wrapping everything), so the order-wrap plan is empty. `apply_order_wraps` takes its `plan.is_empty()` short-circuit (`order_wrapping.rs:432`) and never reaches `lower_order_state` — the consumer-local plan is never applied and no per-record carriers exist. The short-circuit's comment ("safe only because an empty plan makes each one a no-op") no longer holds: `consumer_local_reexport_plan` eligibility is plan-independent.
- Result: placement assumed per-record carriers; emission produced the monolithic barrel. The probe also cannot be rescued by the on-demand force-add (`order_analysis.rs`, `all_at_risk.extend(carrier importers)`) because the interop-wrapped barrel is never order-wrap-eligible, which is why both strict modes fail.

Minimality notes (each verified): one shared forwarder instead of two makes routing union the demand (no split, passes); collapsing the two leaves into one file gives the leaf both entry bits (placed beside the barrel, passes); any plain `WrapKind::None` ESM module in the graph makes the plan non-empty, lowering runs, and the output is correct.

### Suggested direction

Run the consumer-local lowering even when the ordinary order-wrap plan is empty (move the `consumer_local_reexport_plan` application out of the `plan.is_empty()` short-circuit), or gate the pre-chunk probe on lowering actually running. The former preserves the #10488 optimization for require-heavy graphs, which are exactly its target.

### Related but distinct

The same seven-file shape with default **esm** output already fails on pre-merge main (`entryA.a === undefined`, silently — no chunk split involved, so it is a different, older bug and stays broken on both sides of the #10488 merge). Filing separately; fixing this issue will not fix that one.

**Comment by IWANABETHATGUY** [comment]
This issue was found by GPT Sol after the PR was merged.
