### ISSUE TITLE
[Bug]: CJS subpath import in lazy chunk throws "X is not a function" — chunk-split interop mismatch in rolldown 1.0.0 / 1.0.1

### ISSUE THREAD

**Issue by thedoublejay** [rolldown/rolldown#9441]
## Reproduction link or steps

**Repo (starting point, see "partial repro" note below):**
<https://github.com/thedoublejay/rolldown-chunk-split-cjs-repro>

**Open in Stackblitz:**
<https://stackblitz.com/github/thedoublejay/rolldown-chunk-split-cjs-repro>

```bash
git clone https://github.com/thedoublejay/rolldown-chunk-split-cjs-repro
cd rolldown-chunk-split-cjs-repro
npm install
npm run build       # vite 8.0.13, rolldown 1.0.1
npm run preview     # browse http://localhost:4173
```

The repo sets up the same conditions where a real-world Vite 8.0.13 build broke:

- 3 × `React.lazy(() => import(...))` boundaries, all importing the same `lodash/<sub>` CJS submodules (forces rolldown to extract them to a shared vendor chunk)
- ESM libs (`@mui/material`, `@tanstack/react-query`, `clsx`, `@emotion/react`) mixed with the CJS modules in the shared chunk, matching the real failing chunk's shape
- `tss-react/mui` `withStyles` in a lazy component (matches the legacy component that surfaced the bug)
- `vite.config.js` mirrors the failing config's distinctive flags: `react({ jsxImportSource: "@emotion/react" })` + `rolldown.moduleTypes: { ".js": "jsx" }`

### **Important — partial repro**

This standalone repo **does not yet trigger the broken emission on its own** — rolldown emits a consistent interop shape here. The same Vite/rolldown versions + the same lodash subpaths + the same lazy boundary structure DO reproduce in a larger codebase (~5000 modules / ~1200-source vendor chunks). The trigger appears to depend on graph shape we couldn't isolate down to a small case.

I'm filing this rather than waiting because the production-side evidence below is concrete (minified output + bisect-narrowed regression range), and a maintainer hint at the chunking heuristic that changed between rolldown `1.0.0-rc.18` and `1.0.0` / `1.0.1` would let me push the repo over the edge. Happy to invest more time on shrinking the case.

## What is expected?

When rolldown splits a CJS module into a separate output chunk, the import-site code and the export-side emission should agree on the interop shape:

- Either both sides treat the export as a `__commonJSMin(...)` lazy-wrapper function, **or**
- both sides treat the export as a static namespace value.

This is what rolldown `1.0.0-rc.18` (shipped in Vite `8.0.11`) does, and what the same source produces correctly there.

## What is actually happening?

In rolldown `1.0.0` / `1.0.1`, when a CJS module ends up in a separate output chunk (not the main bundle), the importer and exporter disagree:

- The **import-site** emits `a(c())` — i.e. calls `c` as a `__commonJSMin()` lazy-wrapper, then passes the result to `_interopRequireDefault`.
- The **export-side** emits the resolved module namespace directly as the export, not wrapped in a callable getter.

Result: `TypeError: <minified> is not a function` thrown synchronously at top-level of the lazy chunk (before any of its `export` bindings evaluate), which surfaces as a `React.lazy` rejection caught by the nearest `ErrorBoundary`.

### Real-world emitted code (anonymized)

```js
// Importing chunk (lazy)
import { Vt as t, fi as n, p as r, q as i, vi as a } from "./main.js";
import { n as s } from "./shared-A.chunk.js";
import { T as c } from "./shared-B.chunk.js";   // ← shared CJS+ESM vendor chunk

var l = a(n()),     // ← works: n() returns the __commonJSMin wrapper from main
    u = a(i()),     // ← works: i() returns the __commonJSMin wrapper from main
    d = a(c())      // ← throws: c is not callable, exporter emitted a value
```

### Browser console

```
TypeError: c is not a function
    at app.<hash>.chunk.js:1:272
Caused by: React ErrorBoundary TypeError: c is not a function
    at Lazy (<anonymous>)
    at Suspense (<anonymous>)
```

Reproducible with both `lodash@4.17.23` and `lodash@4.18.1`, both `@vitejs/plugin-react@6.0.0` and `@vitejs/plugin-react@6.0.2`, so neither of those is the variable.

## System Info

```Shell
System:
  OS: macOS 26.5
  CPU: arm64 Apple Silicon
Binaries:
  Node: 24.14.1
  npm: 11.11.0
  Yarn: 4.13.0
npmPackages (broken configuration):
  vite: 8.0.13
  rolldown: 1.0.1 (transitive via vite)
  @vitejs/plugin-react: 6.0.2
  react / react-dom: 19.2.x
```

### Bisect: which Vite/rolldown versions are affected?

| Vite version | Bundled rolldown | Status |
|---|---|---|
| 8.0.1  | `1.0.0-rc.10` | ✅ works |
| 8.0.11 | `1.0.0-rc.18` (Apr 29, 2026 — last RC) | ✅ works |
| 8.0.12 | `1.0.0` (May 7, 2026 — first stable) | ⚠️ likely affected (same rolldown family) — not directly retested |
| 8.0.13 | `1.0.1` (May 13, 2026) | ❌ reproduces |

Bisect was carried out against the real-world failing app: same source, same install, only the Vite/rolldown version changed.

### Workaround in use

Pin Vite to exact `8.0.11`.

### Related

- [#9407](https://github.com/rolldown/rolldown/issues/9407) — distinct bug, same rolldown 1.0.1 family: `require("react")` left as runtime `__require` even when react is inlined elsewhere in the same build. Different surface (SSR + dangling `__require`) but same theme of CJS-interop emission inconsistency across the bundle graph.
- [#7449](https://github.com/rolldown/rolldown/issues/7449) — incorrect execution order with CJS + advancedChunks (different mechanism, but also CJS chunking-related).

### Triage hint

If a maintainer can hint at what specifically changed in chunk emission between rolldown `1.0.0-rc.18` and `1.0.0` / `1.0.1` for shared CJS modules — particularly when a vendor chunk mixes ESM and `__commonJSMin`-wrapped CJS modules — I should be able to take the linked repo over the edge into a clean standalone repro.

**Comment by IWANABETHATGUY** [comment]
I think you could use AI to automatically search for the minimal reproduction. Or at least, give us a **reproduction** so we could make it smaller with AI.

**Comment by thedoublejay** [comment]
Sorry, having a hard time creating a small reproducible version. The default chunker stays cycle-free at every shape I try at small scale. But I dug into your release notes and think I've narrowed the suspect range enough to share.

The chunker change between rc.18 and 1.0.1 came from two PRs:

- v1.0.0 [#9270](https://github.com/rolldown/rolldown/pull/9270) - *implement dynamic dominator merge logic*
- v1.0.1 [#9305](https://github.com/rolldown/rolldown/pull/9305) - *chunk-optimization: dedupe already-loaded dynamic deps*

#9305 fixed [#9331](https://github.com/rolldown/rolldown/issues/9331) (CJS facade case - I confirmed it builds cleanly), but appears to mis-handle an adjacent shape.

### Evidence on the failing app — same source, only rolldown version changes

| vite (rolldown) | Cyclic chunk imports |
|---|---|
| 8.0.11 (`1.0.0-rc.18`) | **0** |
| 8.0.13 (`1.0.1`)       | **8678** |

Smallest cycle:

```text
big-vendor.chunk.js   (1.7 MB, lodash + @mui + @tanstack + 700+ app sources)
  imports "t as Wd" from
mid-legacy.chunk.js   (34 KB, 2 legacy form components)
  imports "t as w" from
button.chunk.js       (9 KB, a legacy <Button1> using lodash/get)
  imports "T as c" from
big-vendor.chunk.js   ← cycle closes back
```

`T as c` is lodash/get's `__commonJSMin` wrapper. The cycle puts that `var` binding in TDZ-equivalent state when Button1's top-level `var d = a(c())` runs, so `c` reads `undefined` → `TypeError: c is not a function`.

Shapes I tried that all stayed cycle-free: the #9331 fixture verbatim, 3-way util cycles, multi-entry overlap, scaled-up shared registries, forced `.cjs` cycles. The trigger seems to need the real app's graph shape (~5000 modules).

If anyone close to #9270 / #9305 has a sense of which graph shape would defeat the intersection check downstream of nested dynamic imports, a pointer would let me build a clean repro. Otherwise feel free to close - I'll re-open with a minimal case if I find one.

**Comment by IWANABETHATGUY** [comment]
At least create a reproduction, please, it does not need to be small if you think it is hard.

**Comment by jacobg** [comment]
I'm also getting weird errors like this since updating from rolldown 1.0.0 to 1.0.1:
```
Document.ts:29 Uncaught (in promise) TypeError: ae is not a function
    at Document.ts:29:2
```
`ae` is some imported value from a bundled module, not sure what it is even.

**Comment by TheAlexLichter** [comment]
@jacobg this is unfortunately not enough for a reproduction. we need code (worst case a whole app) to reproduce this.

**Comment by IWANABETHATGUY** [comment]
> I'm also getting weird errors like this since updating from rolldown 1.0.0 to 1.0.1:
> 
> ```
> Document.ts:29 Uncaught (in promise) TypeError: ae is not a function
>     at Document.ts:29:2
> ```
> 
> `ae` is some imported value from a bundled module, not sure what it is even.

Can you try to override rolldown with `https://pkg.pr.new/rolldown/rolldown@886329c`?If it still solve your issue can you just file another issue with proper reproduction ?

**Comment by jacobg** [comment]
@IWANABETHATGUY   @TheAlexLichter Thanks, but unfortunately, that test build does not fix my error. I'm not sure how to make an MRE without sharing my entire app. I'd be willing to do a Zoom meeting screenshare to discuss and present, if that interests you.

**Comment by kjanoudi** [comment]
We have the same issue in our app, and pinning back to 8.0.12 on vite fixes it

**Comment by jacobg** [comment]
> We have the same issue in our app, and pinning back to 8.0.12 on vite fixes it

You shouldn't need to pin vite since it's a rolldown issue. You can just add to your package.json:
```json
  "overrides": {
    "rolldown": "1.0.0"
  },
```

**Comment by kjanoudi** [comment]
Opened #9466 with a fix candidate for one shape reported on this issue.

**Shape addressed**: CJS-facade module (or wrapped-ESM module) shared between a static entry and one or more *effective* dynamic-entry chunks. Since 1.0.1 (PR #9305) the wrapper gets merged into the static entry and sibling dynamic chunks emit a static back-import:

```js
// dynamic-child.js
import { t as require_X } from "./entry.js";
var import_X = require_X();
```

Under pure ESM this is fine — the dynamic edge postpones the child's evaluation until after the entry body has run. Under static-wrapper composition (Cloudflare Workers SSR, react-router 7 SSR route manifests, miniflare, etc.) the child evaluates before the entry body completes and hits TDZ → `TypeError: require_X is not a function` (surfaces as Cloudflare 1101 in deployed Workers; `__exportAll is not a function`, `e is not a function`, etc. in the issue reports here).

Minimal repro: https://github.com/kjanoudi/rolldown-9441-repro — lifted verbatim from the regression-lock fixture introduced by #9351. vite 8.0.13 (rolldown 1.0.1) → wrappers in entry + back-import; vite 8.0.12 (rolldown 1.0.0) → wrappers in shared chunks, no back-import.

**Why it doesn't blanket-revert #9305**: the discriminator is whether the dropped dynamic entries are *effective* (their module body emerges as a separate chunk and back-imports) or *ineffective* (their body is also statically reached by the surviving parent, like #8361 / #8361_2). The PR fires only on the effective case, so #8361's cycle assertion stays green.

**Shapes this PR does *not* address**: the true 3-chunk cycle reported by @thedoublejay (`big-vendor → mid-legacy → button → big-vendor`) involving vendor chunks + manual splits is a different shape — a real chunk-graph cycle, not a TDZ. The two are worth keeping separate.

**Comment by daniele-orlando** [comment]
I have the same error in my app bundled with Vite. The error has been introduced with Vite `8.0.13`. Vite `8.0.12` and below works fine.

**Comment by TheAlexLichter** [comment]
@kjanoudi @daniele-orlando we still have no proper reproduction so fixing this is really difficult. some code (even not minimal) to reproduce it would be ideal

**Comment by jacobg** [comment]
@TheAlexLichter How would providing access to a repro work? I guess if we could be assured that one person be given clone access, it won't be forked, shared publicly or privately, or kept around after fixing the bug, then I think we'd be open to providing access. I would be comfortable sharing it exclusively with you, since you are well known person. Thanks.

**Comment by TheAlexLichter** [comment]
@jacobg best would be to reduce your code while the project still exposing the issue, either manually or via AI.

If this didn't work (I remember you said so on your Discord messages) then yes, invite me and I can look into it. I won't share the code or fork it.

**Comment by jacobg** [comment]
@TheAlexLichter AI wasn't able to reduce it substantially and repro it. I guess I'll manually remove obvious irrelevant stuff, and share it with you. I'll keep you posted. Thanks.

**Comment by daniele-orlando** [comment]
@TheAlexLichter yesterday I invested some time trying to reduce the code of my (huge) app to a minimum reproducible example, but changing the app graph made the error disappear. Unfortunately I can't publish the app as is. I'll try tomorrow and in case I succeed I'll publish the reproduction.

**Comment by kjanoudi** [comment]
@TheAlexLichter im sorry, i have not had a chance to take another look at this. Pinning it to 1.0.0 helped us. If it helps, i can share our vite config, github action, and wrangler setup privately.

**Comment by TheAlexLichter** [comment]
@daniele-orlando thanks! Yes, that's the issue with module graph / chunking issues. but maybe you can replace existing business logic with stub functions

@kjanoudi I understand that. Best would be a reproduction to reliably see the error, ideally public. Same as above.

**Comment by jacobg** [comment]
@TheAlexLichter I've invited to share my repro with you on github. com. Please let me know if you received it or not.

I removed some extraneous stuff more around converting this web app to a native app. The web part is basically the original.

The `main` branch is on rolldown 1.0.0, and works fine. You can run:
```
npm i
npm run build
npm run preview
```
Then go in browser to: http://localhost:4173, and you'll see the page loads fine.

Then check out branch `rolldown-1.0.2`, and repeat the process. You'll see the page fails to load with this error
```
Uncaught (in promise) TypeError: ae is not a function
    at Document.ts:29:2
```

If you go to vite.config.ts and uncomment the line `minify: false`, then you'll see a more descriptive error like this:
```
Document.ts:29 Uncaught (in promise) TypeError: require_lodash is not a function
    at Document.ts:29:2
```

Please let me know if you have any questions.

Thanks!

**Comment by IWANABETHATGUY** [comment]
> [@TheAlexLichter](https://github.com/TheAlexLichter) I've invited to share my repro with you on github. com. Please let me know if you received it or not.
> 
> I removed some extraneous stuff more around converting this web app to a native app. The web part is basically the original.
> 
> The `main` branch is on rolldown 1.0.0, and works fine. You can run:
> 
> ```
> npm i
> npm run build
> npm run preview
> ```
> 
> Then go in browser to: http://localhost:4173, and you'll see the page loads fine.
> 
> Then check out branch `rolldown-1.0.2`, and repeat the process. You'll see the page fails to load with this error
> 
> ```
> Uncaught (in promise) TypeError: ae is not a function
>     at Document.ts:29:2
> ```
> 
> If you go to vite.config.ts and uncomment the line `minify: false`, then you'll see a more descriptive error like this:
> 
> ```
> Document.ts:29 Uncaught (in promise) TypeError: require_lodash is not a function
>     at Document.ts:29:2
> ```
> 
> Please let me know if you have any questions.
> 
> Thanks!

Could you also extend an invitation to me?

**Comment by IWANABETHATGUY** [comment]
Can you try overriding rolldown with `https://pkg.pr.new/rolldown/rolldown@9514` and test whether the issue is fixed?

**Comment by daniele-orlando** [comment]
@IWANABETHATGUY I have tried with the PR rolldown package and in my case it resolves the issue. I don't have the runtime error anymore.

**Comment by TheAlexLichter** [comment]
should also be fixed in @jacobg's repro according to my test.

**Comment by jacobg** [comment]
@TheAlexLichter @IWANABETHATGUY Thank you! Works great now!
