### ISSUE TITLE
[Bug]: per-entry reachability moves an initializer behind a statically imported shared chunk

### ISSUE THREAD

**Issue by shining-mind** [rolldown/rolldown#10787]
### Reproduction link or steps

[Rolldown REPL reproduction](https://repl.rolldown.rs/#eNqNVE1v2zAM/SucMNQO4CjYsJOD7LAvYJddtmGHukBVi7bVypIh0Uu3wP99kGKnTuoCuxgwH8nH90j7wCqWH5h35aYVyvB7H14Ny89CGStZzlTbWUdwANWKGn86nYHyX40iJbT6ixIGqJxtIeGbO+Ecan7vk21hClNa461Grm2dJqEpqKeyPLnok65W28WaQBuzR/5VbC72QhEch0sTvulEjYE5oCxjyHJyPQ5ZVDSCc5FT6AWR/6mqW5iNjaRB7AXpFDqS1treCf2jUZ4L75E+CB+pd5B2gpoV7N7DbUPU+XyzKaXh+CjaTiMn9LR5fQhJw20cCh/j/GE2mrsMOwg2zKY6qZnP9RS8tGNxz6OMZE5d9aYkZc3lUuFQGACH1Luz/W8LM8zKF52v0aAThHId/RkpJyXP0bmkBfSo7dyqiXQHL2wjTRzuhZO8M3UyrddZraXdG15aU6l6Rr2AXFgqsVIGP0b4pHUqO7NUYiV6TWcV6aEwBSnT9ZSP189bJMFjKAug7SmiMbMgqVwezJTK09php5PsCFTWtYJySNC3UwwNuT9flMZvokWfQzL+Cya8bHrzMMevjWjxZn3dCN/cjIkAAKVGYT4F6nB/MTjEJzlE34gHzI+XAdBa2Wv8riR+riosyadKribwdDqvlORopP+lqEmT2Ue5gqurS3ThcMLqQrvhNMtw3OaQsd8sZ2/4W/6ODf8AXkHCQg==)

The REPL is saved with Rolldown 1.2.4. Only `main.js` is selected as a configured input. It dynamically imports `page.js`, which Rolldown treats as a dynamic entry during automatic code splitting.

Both the initial entry and the dynamic entry consume `imageUrl` through `barrel.js`, so `generated-asset.js` is shared between them. `init.js` is used only by the initial entry. `barrel.js` and `generated-asset.js` are marked with `moduleSideEffects: false`; the generated asset has a used export whose initializer calls a global function installed by `init.js`.

Steps:

1. Open the REPL with Rolldown 1.2.4.
2. Inspect the generated `main.js`, the shared `generated-asset-*.js` chunk, and the dynamic `page-*.js` chunk.
3. Execute the generated `main.js` with Node, or download/copy the files and run:

   ```sh
   pnpm add --save-dev --save-exact rolldown@1.2.4
   pnpm exec rolldown -c
   node dist/main.js
   ```

4. Change the Rolldown version to 1.1.4 and repeat.

Results:

- 1.1.4: passes.
- 1.1.5: fails.
- 1.2.4: still fails.

The 1.1.4 output places `init.js`, `generated-asset.js`, and `barrel.js` in the same shared chunk, with the initializer first:

```js
globalThis.assetBaseUrl = /* ... */;
const imageUrl = globalThis.assetBaseUrl('reward.png');
```

Starting with 1.1.5, `generated-asset.js` is split into a shared chunk that is statically imported by both the initial and dynamic entries. The output becomes equivalent to:

```js
// generated-asset.js
const imageUrl = globalThis.assetBaseUrl('reward.png');

// main.js
import { imageUrl } from './generated-asset.js';
globalThis.assetBaseUrl = /* ... */;
await import('./page.js');

// page.js
import { imageUrl } from './generated-asset.js';
```

Because ESM evaluates static dependencies before the importing module body, the shared generated-asset chunk runs before the initializer in `main.js` and throws. The failure happens while loading the initial entry, before the dynamic import is reached.

### What is expected?

The generated chunks should preserve the observable ESM evaluation order.

When `main.js` is executed, `init.js` must run before `generated-asset.js` evaluates its exported value. Executing the bundle should print:

```text
main initialized: true
main image: https://cdn.example.test/reward.png
page: https://cdn.example.test/reward.png
```

### What is actually happening?

Since Rolldown 1.1.5, `init.js` is placed in the body of `main.js`, while `generated-asset.js` is placed in a shared chunk imported by both `main.js` and the dynamic `page.js` entry.

ESM evaluates the statically imported shared chunk before the body of `main.js`, so the generated asset reads the global before it is initialized:

```text
TypeError: globalThis.assetBaseUrl is not a function
    at .../dist/generated-asset-*.js:2:29
```

The issue is still reproducible with the current Rolldown 1.2.4.

### System Info

```Shell
System:
  OS: macOS 26.3.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 16.00 GB
  Shell: 5.9 - /bin/zsh

Binaries:
  Node: 26.5.1
  Yarn: 3.5.0
  npm: 11.17.0
  pnpm: 11.17.0

Browsers:
  Chrome Canary: 154.0.8025.0
  Firefox Developer Edition: 141.0
  Safari: 26.3.1

npmPackages:
  rolldown: 1.2.4 => 1.2.4
```

### Any additional comments?

The regression boundary and a control experiment point to https://github.com/rolldown/rolldown/pull/10111.

That change made `determine_reachable_modules_for_entry` traverse `meta.load_dependencies` instead of `meta.dependencies`, excluding static record edges to side-effect-free modules from per-entry reachability.

In this reproduction, the new reachability graph assigns the initializer to `main.js` and its consumer to a shared initial/dynamic-entry chunk, producing the invalid runtime order. With tree-shaking disabled, `load_dependencies` equals `dependencies` and the same project works on Rolldown 1.1.5 and 1.2.4.

This was originally observed in a Vite application. Vite does not add the application pages to the configured `input`; they are loaded with dynamic imports and become dynamic entries inside Rolldown's automatic code splitting. The affected component is also statically reachable from the initial application entry, so its generated asset module is shared between the initial entry and multiple dynamic page entries. The S3 bootstrap module that installs the global URL resolver is reachable only from the initial entry.

Concretely, the real graph contains these paths:

```text
initial entry
├─ webapp init
│  └─ s3.ts
│     └─ sets globalThis._imagesBaseUrl
├─ app
│  └─ scanner dialog
│     └─ reward banner
│        └─ generated asset
│           └─ calls globalThis._imagesBaseUrl() during module evaluation
└─ router
   └─ import(check page) [dynamic entry]
      └─ reward banner
         └─ generated asset [same shared module]
```

`s3.ts` is reachable only from the initial entry. The generated asset is reachable from both the initial entry and the dynamic entry, so code splitting places it in a shared chunk. Starting with 1.1.5, that shared chunk is statically imported by the initial chunk and therefore evaluates before the initial chunk body that contains `s3.ts`.

The Vite asset plugin returns the generated module with `moduleSideEffects: false`; its used exported value is computed at module evaluation time using the global URL resolver. Vite dev works, while the production code-split bundle fails. The reproduction reduces the initial-entry path to a direct use of `imageUrl`, but preserves the same initializer-only-in-initial-entry and consumer-shared-with-dynamic-entry reachability pattern.

No plugin is required for the minimal reproduction: the plugin metadata is modeled with `treeshake.moduleSideEffects`.

We also tested `output.strictExecutionOrder: true`. It prevents this specific `_imagesBaseUrl` failure, but it is not a viable workaround for the application. The option globally changes module execution by wrapping module bodies in `init_*` functions to reconstruct source order. With it enabled, the application no longer fails on the generated asset, but multiple unrelated parts fail during startup and the application still ends on a blank screen. We did not reduce those additional failures because they belong to the separate strict-execution-order path; this report is about the deterministic regression in the default output mode.

### Related issues and why this is distinct

I searched both open and closed issues in `rolldown/rolldown` and `vitejs/vite`. The closest reports cover the same broad class of execution-order failures, but none matches this reproduction's trigger and regression boundary:

- [vitejs/vite#21866](https://github.com/vitejs/vite/issues/21866) and [rolldown/rolldown#9007](https://github.com/rolldown/rolldown/issues/9007) discuss top-level initialization that becomes reordered after code splitting, with `strictExecutionOrder` as the workaround. Those reports were treated as the general code-splitting limitation; their reproductions involve CommonJS/polyfill handling or a large graph with circular imports, and the behavior was not specific to Rolldown 1.1.5. This reproduction is a five-module pure-ESM graph, uses default chunking with one configured input and one dynamic entry, has no source-level cycle, and has an exact 1.1.4-working / 1.1.5-broken boundary caused by the per-entry reachability change.
- [rolldown/rolldown#9993](https://github.com/rolldown/rolldown/issues/9993), its still-open follow-up [#10673](https://github.com/rolldown/rolldown/issues/10673), and [#10228](https://github.com/rolldown/rolldown/issues/10228) produce a similar generated entry/consumer cycle, but all involve Rolldown's CommonJS runtime helpers. This reproduction contains only user-authored ESM and fails because a user initializer and its used consumer are assigned to different entries. In particular, #10673 notes that its remaining entry-order case also fails on 1.0.3, while this case works through 1.1.4.
- [rolldown/rolldown#10688](https://github.com/rolldown/rolldown/issues/10688) loses a side-effect chunk entirely after constant inlining through a `sideEffects: false` barrel. Here no required chunk is orphaned: the initial, dynamic, and shared chunks are emitted and linked, but the generated static import forces the consumer to execute before the initializer.
- [rolldown/rolldown#10690](https://github.com/rolldown/rolldown/issues/10690) drops an `init_*()` call from a wrapped shared chunk under `strictExecutionOrder`, starting with 1.2.1. This reproduction does not enable `strictExecutionOrder` or on-demand wrapping, emits no `init_*` wrappers, and starts failing in 1.1.5.

For completeness, current Rollup produces the same failing chunk topology. This may therefore be related to Rollup-compatible `moduleSideEffects` semantics, but it still represents a deterministic runtime regression from Rolldown 1.1.4 and creates an ESM initialization-order cycle.
