### PR TITLE
revert: "fix: jsx preserve break component which is default export (#5764)"

### LINKED ISSUE #5847: [Bug]: Compromise library not working in development anymore
### Reproduction link or steps

https://stackblitz.com/edit/github-z3jerszh-yzc4e3uh?file=package.json,src%2Fmain.ts

### What is expected?

Development should work like production. Regressed fairly recently. Broken in 7.1.2, worked in 7.0.12

### What is actually happening?

It crashes in development, maybe due to some local scope issues?

```
Uncaught TypeError: nlp$1.addTags is not a function
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by shulaoda**
closes #5847

### CODE REVIEW

**Comment by shulaoda** [comment]
* **#5856** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5856?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5856?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by IWANABETHATGUY — APPROVED** [review]
