### ISSUE TITLE
[Bug]: `__commonJSMin` runtime ⟷ shared chunk cycle still occurs after #10101 (orphan CJS side-effects, default chunking)

### ISSUE THREAD

**Issue by SinnerAir** [rolldown/rolldown#10906]
### Reproduction link or steps

Minimal repo: https://github.com/SinnerAir/rolldown-commonjs-cycle-repro

```bash
npm install
npm run repro   # gen sources → vite build → load a built entry
```

Setup: `@babel/preset-env` 8 + `babel-plugin-polyfill-corejs3` (`method: 'usage-global'`, core-js 3.50) injecting polyfills on API usage across 20 entries. **Default automatic code splitting — no `advancedChunks`** (unlike #9887).

The array-buffer / typed-array / uint8-array core-js modules it injects are side-effect-only with no reachable consumer (orphans); their internal circular `require()`s force the lazy `__commonJSMin` wrapper.

### What is expected?

The build runs without errors (`run.mjs` prints `OK — no cycle`).

### What is actually happening?

```
REPRODUCED: TypeError - require_es_array_buffer_detached is not a function
```

Rolldown emits a `runtime ⟷ shared` import cycle.

`chunks/rolldown-runtime.*.js`
```js
import { /* … */ x as require_es_array_buffer_detached } from "./shim.*.js";
require_es_array_buffer_detached();   // top-level call of an orphan side-effect
// … 10 more orphan side-effect calls …
var __commonJSMin = (cb, mod) => () => (mod || (cb((mod = { exports: {} }).exports, mod), cb = null), mod.exports);
export { /* … */ __commonJSMin as t };
```

`chunks/shim.*.js`
```js
import { t as __commonJSMin } from "./rolldown-runtime.*.js";   // imports the helper back
var require_fails = __commonJSMin((exports, module) => { /* core-js internal */ });
// … the orphan module definitions live here …
```

`runtime` top-level-calls the orphan side-effects imported from `shim` before `shim` has finished initializing. `shim` is blocked importing `__commonJSMin` from `runtime`, so the accessor is still undefined → `is not a function`.

### System Info

```Shell
  System:
    OS: Windows 11 10.0.26200
    CPU: (16) x64 AMD Ryzen 7 8845HS w/ Radeon 780M Graphics
    Memory: 17.53 GB / 31.31 GB
  Binaries:
    Node: 24.15.0
    Yarn: 1.22.22
    npm: 12.0.2
    pnpm: 10.33.4
  Browsers:
    Chrome: 152.0.7977.83
    Edge: Chromium (152.0.4191.62)
    Firefox: 155.0.1
  npmPackages:
    rolldown: 1.2.9 => 1.2.9
    vite: ^8.3.0 => 8.3.0
```

### Any additional comments?

Same helper and failure class as #9993, which was closed by #10101 ("follow entry facade edges in runtime placement cycle check"). #10101 fixed the original shape, but the runtime-placement cycle check still misses this graph shape. First reported as a follow-up in https://github.com/rolldown/rolldown/issues/9993#issuecomment-4937000046; opening a separate issue as requested by @hyfdev.

Reproduces on rolldown 1.1.5 / vite 8.1.4 and still on the latest rolldown 1.2.9 / vite 8.3.0.

Real-world impact: a production Vite 8 app had to drop core-js usage polyfills from its build to avoid `is not a function` on every page.

Possibly related: #10008 (tracking), #10673, #10787, #10863.

**Comment by hyfdev** [comment]
You shouldn't let babel plugin touch `\0rolldown/runtime.js` module.

**Comment by SinnerAir** [comment]
Thanks @hyfdev, confirmed — that was the root cause.

The transform filter only checked `.js$` and `node_modules`, so `\0rolldown/runtime.js` went through Babel and `babel-plugin-polyfill-corejs3` injected core-js imports straight into the runtime module. Skipping virtual modules fixes it:

```js
async transform(code, id) {
    if (id.startsWith('\0')) return;
    // ...
}
```

With that guard the repro prints `OK — no cycle` on rolldown 1.2.9 / vite 8.3.0. Sorry for the noise, and thanks for the quick look!
