### ISSUE TITLE
[Bug]: `__commonJSMin is not a function` — runtime helper lifted into entry chunk again in 1.1.2 (regression of #9224)

### ISSUE THREAD

**Issue by thevuong** [rolldown/rolldown#9993]
### Reproduction link or steps

This is a **regression in rolldown 1.1.2 of the bug fixed for #9224** (which was itself a rc.17 regression from rc.15). The runtime CJS-interop helper (`__commonJSMin`) is once again lifted into the **entry chunk** and re-imported by a code-split CJS chunk that is evaluated *before* the entry body runs, so the helper is still uninitialized at the call site → `TypeError: __commonJSMin is not a function`.

I don't have a minimal REPL (same as #9224 — the trigger is a real dependency graph), but the before/after is fully deterministic. It surfaces via **vite**, whose only dependency delta between the working and broken versions is the bundled rolldown:

| vite | bundled rolldown | result |
| --- | --- | --- |
| 8.0.16 | `1.0.3` | ✅ works |
| 8.1.0 | `~1.1.2` | ❌ `__commonJSMin is not a function` |

Stack (TanStack Start SSR prerender of a Vite app; Node ESM evaluating the server function):

```
TypeError: __commonJSMin is not a function
    at .../functions/__server.func/_libs/@tanstack/react-router+[...].mjs:3917:71
    at .../functions/__server.func/recharts+[...].mjs:15:71
```

### The before/after that pins it

**rolldown 1.0.3 (works)** — helper lives in a dedicated *leaf* runtime module `_runtime.mjs` (no imports → always initialized before any consumer):

```js
// _libs/recharts+[...].mjs
import { n as __exportAll } from "../_runtime.mjs";   // leaf helper module, no cycle
```

**rolldown 1.1.2 (broken)** — helper is inlined into the **server entry** `_ssr/ssr.mjs` (hoisted `var`, exported `as s`) and re-imported by sibling chunks:

```js
// recharts+[...].mjs  (and _libs/@tanstack/react-router+[...].mjs, etc.)
import { c as __exportAll, l as __require, s as __commonJSMin, u as __toESM } from "./_ssr/ssr.mjs";
//                                          ^^^^^^^^^^^^^^^^^ imported from the ENTRY chunk
var require_use_sync_external_store_shim_production = __commonJSMin((exports) => { ... }); // top-level call

// _ssr/ssr.mjs  (the entry)
var __commonJSMin = (cb, mod) => () => (mod || (cb((mod = { exports: {} }).exports, mod), cb = null), mod.exports);  // line 14
...
export { ..., __commonJSMin as s, ... };
```

Because `_ssr/ssr.mjs` is the entry, it imports the route/lib chunks at its top; ESM evaluates those imports depth-first **before** the entry body assigns the `var __commonJSMin`, so the live binding is still `undefined` when the sibling chunk runs its top-level `__commonJSMin(...)`.

This is exactly the cycle shape described in #9224. It reproduces with **default chunking** — removing a manual `output.codeSplitting.groups` entry for one library just moves the failure to the next CJS-wrapped sibling chunk (e.g. `@tanstack/react-router`), confirming it is the general runtime-helper-in-entry placement, not a specific group config (so it is distinct from the `advancedChunks`-specific #9887, though likely the same underlying cause).

### What is expected?

The `__commonJSMin`/`__commonJS` runtime helper should be emitted so it is initialized before any consumer — e.g. inlined into the chunk that needs it, or kept in a dependency-free leaf module like rolldown 1.0.3 emitted (`_runtime.mjs`) — never lifted into an entry chunk that imports its own consumers, which creates the circular ESM init.

### What is actually happening?

In rolldown 1.1.2 the helper is placed in the entry chunk and imported by code-split CJS chunks that execute first, throwing `__commonJSMin is not a function` at module-init. Pinning rolldown back to 1.0.3 (via vite 8.0.16) avoids it.

### Versions

- rolldown 1.1.2 (broken) / 1.0.3 (works), as bundled by vite 8.1.0 / 8.0.16
- @tanstack/react-start SSR prerender, nitro 3.0.260610-beta, Node 24/26

**Comment by IWANABETHATGUY** [comment]
I am not sure whether you have set`codeSplitting.includeDependenciesRecursively` to `false`

I could only reproduce it with `codeSplitting.includeDependenciesRecursively: false`

https://repl.rolldown.rs/#eNptkttSgzAQhl8lk5u2Y4uH0ps6XqkvoN4ZpxNhwXTSBHOg7VDe3RwKPQgXwP777+4XlgYXeNlgIXOYJ9lahwAvz4QpzlxccvlN+ccP08lqpWE1R09o/F88HNDdBN2g+0ciaslypODXMgXjUXLrWy6StR5NXBJ2lVRGJ14MzeZOdLMAL42y0E4DQXqNFIVhpHQIKb1Aupjq/enQVA95PjTEwzMXQzMXl5+BKhTmeW/TOiVGSU25BactejDUdE5vww5HSc5zuRVJJkXBysT0YAOZiMg2x1Y5FEzAc0ijFhVKbtCoKxsR0U91Rmp5ePYF44YIhAhmorKG4CUKsVdAGLWf3XuNnHZC8PTS8HAyhP+IYJ9vg4vgSoEGVcOr976zUlBjnRRrKOdyO4OdAaGZFMfWBEtrrmEy1/694swYJsqzTETPuM3hBSoQOYiMgX6DzCrNauB7by4o13Dk9hWlkrYKEJ+diE4do0fQDUTMuj9zlzOgA1489ufdLP2Kx45X271+xZcQu1s78ct2267d+jj1XXD7BxI4JKs=

**Comment by thevuong** [comment]
Thanks @IWANABETHATGUY — a few findings.

**Standalone runnable repo for your REPL shape:** https://github.com/thevuong/rolldown-9993-repro (`npm install && npm run repro`)

### Bisect

The regression was introduced in **1.1.1** and is **still present in 1.1.3** (latest):

| rolldown | result |
| --- | --- |
| 1.0.3 | ✅ ok (helper in a dependency-free leaf chunk) |
| 1.1.0 | ✅ ok |
| **1.1.1** | ❌ regression introduced here |
| 1.1.2 | ❌ (originally reported) |
| **1.1.3** | ❌ still broken |

### Confirmed in the real app with DEFAULT config (no `includeDependenciesRecursively: false`)

This is the important one. I rebuilt my actual failing app (TanStack Start + nitro + recharts, vercel preset) on vite 8.1.0 and it throws during SSR prerender:

```
[prerender] Crawling: /
TypeError: __commonJSMin is not a function
```

The server build uses **nitro's default** code-splitting, which is:

```js
codeSplitting: { groups: [{ test: /node_modules/, name: libChunkName }] }
```

i.e. `includeDependenciesRecursively` is left at its default (**true**) — the flag from your REPL is **not** set anywhere. So the bug is not gated on that flag; nitro's default chunking reaches the same bad placement.

The emitted layout matches the report exactly — there is **no** dependency-free `_runtime.mjs` leaf; instead `__commonJSMin` is defined in the **entry** and re-imported by sibling chunks:

```js
// _ssr/ssr.mjs  (entry, line 14)
var __commonJSMin = (cb, mod) => () => (mod || (cb((mod = { exports: {} }).exports, mod), cb = null), mod.exports);
export { …, __commonJSMin as s, … };

// _libs/react-is.mjs  (sibling, imported by the entry)
import { s as __commonJSMin } from "../_ssr/ssr.mjs";
var require_react_is_production = /* @__PURE__ */ __commonJSMin((exports) => { … }); // top-level → throws
```

(Sibling chunks importing `__commonJSMin` from the entry: `_libs/react-is.mjs`, `_libs/eventemitter3.mjs`, `_libs/react-redux+[...].mjs`, `_libs/@tanstack/react-router+[...].mjs`.) Reproduces on **both 1.1.2 and 1.1.3**.

Note on minimization: a *small* TanStack Start app (single route) does **not** trip it — rolldown cleanly emits a `_runtime.mjs` leaf there. The bad placement only appears once the graph is large enough to push `__commonJSMin` into the entry, which is why this is hard to shrink into a tiny default-config REPL (same situation as #9224). Your `includeDependenciesRecursively: false` REPL is one reliable small trigger for the same defect.

### Reproduction lever: it scales with the number of CJS-wrapped sibling chunks

I bisected the real app to find what tips the placement (same rolldown 1.1.2, default config throughout):

- **Full app** (~140 dynamic-import chunks; many CJS-wrapped siblings: `react-is`, `react-redux`, `eventemitter3`, `@tanstack/react-router`, the recharts subtree) → `__commonJSMin` is hoisted into the **entry** `_ssr/ssr.mjs` → crash.
- After cutting the graph down (~8 chunks, only `@tanstack/react-router` left as a CJS sibling) → rolldown keeps `__commonJSMin` **inside the `@tanstack/react-router` chunk itself** (self-contained, no external importer) → builds and prerenders clean, **exit 0**.

So the trigger is a placement threshold: **the more chunks share the runtime helper, the more rolldown prefers to hoist it to their common ancestor — which, when that ancestor is an entry that statically imports those same chunks, is exactly the circular layout.** It's not gated on `includeDependenciesRecursively`; that flag is just one small way to force the same hoist. Reducing the number of helper-consuming chunks moves the helper back into a leaf/self-contained chunk and the crash disappears, on the same rolldown version.

### The helper is only the surface symptom — it's a circular cross-chunk init order

I patched the emitted entry so the helper is a **hoisted function declaration** instead of a `var` arrow:

```js
// before: var __commonJSMin = (cb, mod) => () => (…);
// after:  function __commonJSMin(cb, mod) { return () => (…); }
```

That fixes the `__commonJSMin` throw, but the bundle **still crashes** with `require_… is not a function`, because the per-module CJS wrappers (`var require_x = __commonJSMin(...)`) are also top-level value bindings imported across the same cycle, and a `var` value can't be hoisted. So changing only the helper's emit form is not sufficient — the real issue is the **circular cross-chunk evaluation order** of top-level bindings.

### Expected

The invariant being violated: **emitted chunks must not reference another chunk's top-level binding before it is initialized.** Today the output throws a `TypeError` at module-init because two chunks import each other's top-level bindings and one evaluates first. rolldown 1.0.3 emitted a valid layout (a dependency-free `_runtime.mjs` leaf) — proof a correct emit exists for this graph. *How* to restore correctness (placement, evaluation ordering, or making the top-level `require_*()`/helper calls lazy) is up to you; lifting shared helpers into an entry is a legitimate size optimization, it just needs to stay init-safe.

**Comment by SinnerAir** [comment]
### Still reproduces on rolldown 1.1.5 (after #10101) — same `__commonJSMin`, default chunking

Follow-up: the runtime-placement cycle from this issue still occurs on **rolldown 1.1.5 / vite 8.1.4** with the fix from #10101 in place. Same helper (`__commonJSMin`), same failure class, but a graph shape the cycle check in #10101 still misses.

**Minimal self-contained repro:** https://github.com/SinnerAir/rolldown-commonjs-cycle-repro

```
npm install && npm run repro
→ REPRODUCED: TypeError - require_es_array_buffer_detached is not a function
```

**Setup** (nothing exotic): `@babel/preset-env` 8 + `babel-plugin-polyfill-corejs3` (`method: 'usage-global'`, core-js 3.49) injecting polyfills on API usage across ~20 entries. The array-buffer / typed-array / uint8-array core-js families it pulls are **side-effect-only with no reachable consumer** (orphans); their internal circular `require()`s force the lazy `__commonJSMin` wrapper. **Default automatic code splitting — no `advancedChunks`** (this is what distinguishes it from #9887).

**What rolldown emits** — a `runtime ⟷ shared` import cycle:

`chunks/rolldown-runtime.*.js`
```js
import { /* … */ x as require_es_array_buffer_detached } from "./shim.*.js";
require_es_array_buffer_detached();   // top-level call of an orphan side-effect
// … 10 more orphan side-effect calls …
var __commonJSMin = (cb, mod) => () => (mod || (cb((mod = { exports: {} }).exports, mod), cb = null), mod.exports);
export { /* … */ __commonJSMin as t };
```

`chunks/shim.*.js`
```js
import { t as __commonJSMin } from "./rolldown-runtime.*.js";   // imports the helper back
var require_fails = __commonJSMin((exports, module) => { /* core-js internal */ });
// … the orphan module definitions live here …
```

`runtime` top-level-calls the orphan side-effects (imported from `shim`) before `shim` finishes initializing — `shim` is blocked importing `__commonJSMin` from `runtime`, so the accessor binding is still uninitialized → `is not a function`.

Happy to trim the repro further or test a candidate build if that helps.

**Comment by hyfdev** [comment]
I'll take a look

**Comment by SinnerAir** [comment]
@hyfdev ,the problem is still relevant.

**Comment by hyfdev** [comment]
> @hyfdev ,the problem is still relevant.

Please create an issue with the reproduction

**Comment by SinnerAir** [comment]
Opened #10906 with the reproduction (still reproduces on rolldown 1.2.9 / vite 8.3.0).
