### PR TITLE
test(rolldown): regression fixture for #9401

### LINKED ISSUE #9401: [Bug]: circular import generated when using dynamic import and require
### Reproduction link or steps

[REPL](https://repl.rolldown.rs/#eNqNkl9v2jAUxb/KlZ82CQIkW1kz7RFNe9rD9rZMqUluqDfXpv6TQhHfvddOSENFJSSEcu1zj38+vgfWsPzAlK5xnlT/bCxYPlqYsIrqjdRrLn/fC5uUJa/2lRRVqb3belc2/vm5nMM3mH8tVKWVdSAetto4rMt5mdKGwUcvDH4oWDILzmlwLthH0uMuKG3iLfbice9IEPqGU4gKWe6Mx+Mksi6Sc/ZYX4m+INMFmbZa1P3pA2lGPh1oyw1EhiA/HGmlq5KWS4+9RQcLh5MyyFiPGC89ZuwWroQMyYQ4IuTbPF8pz9I69ZwIgmwMEOsrz8/IK3snpDgofUoXtsNbvL87moUh4nDYa8TZEHEAOI84GyI2WspaP6mEJrARm9FVL+x0l57N4DsqNJymDdZ7uKu42WgwXsF0CxdSgOl0LRRs+qayETvnDdIy/SySy026vP2Ufb7N0ptF+iVL0+XybmCuseFeEnuhAIQi17z7BigYKmf203nBcirOcg2K4yT8486hUVzm8Ica+iL0/I3bziDae/4fc2i4tBgXtwYtmhZXwf+X2CgekG04hUupn6bBR1mhVcFiQ3ffgcw6Iyq32mHlHYl+mhrN2B/gQSjR7H+oDmfVTeBYEuC7Z6J3ail4SeFZx44v9fKEMg==)

### What is expected?

No error happens when executing `dist/entry-0.js`.

### What is actually happening?

The following error happens when executing `dist/entry-0.js`:
```
TypeError: __exportAll is not a function
    at dist/node3-DAmMu6Zs.js:3:37
    at ModuleJob.run (node:internal/modules/esm/module_job:430:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:661:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
```
In other words, the cyclic import "entry-0 -> node3 -> entry-0" is not output.

### System Info

```Shell
System:
    OS: Windows 11 10.0.26200
    CPU: (32) x64 AMD Ryzen 9 9950X 16-Core Processor            
    Memory: 12.93 GB / 31.06 GB
  Binaries:
    Node: 24.14.1 - C:\Users\green\.vite-plus\js_runtime\node\24.14.1\node.EXE
    Yarn: 1.22.22 - C:\Users\green\.vite-plus\js_runtime\node\24.14.1\yarn.CMD
    npm: 11.11.0 - C:\Users\green\.vite-plus\js_runtime\node\24.14.1\npm.CMD
    pnpm: 10.33.4 - C:\Users\green\.vite-plus\js_runtime\node\24.14.1\pnpm.CMD
    bun: 1.3.13 - C:\Users\green\AppData\Local\Microsoft\WinGet\Links\bun.EXE
    Deno: 2.7.12 - C:\Users\green\AppData\Local\Microsoft\WinGet\Links\deno.EXE
  Browsers:
    Chrome: 148.0.7778.98
    Edge: Chromium (147.0.3912.98)
    Firefox: 150.0 - C:\Program Files\Mozilla Firefox\firefox.exe
    Internet Explorer: 11.0.26100.8115
  npmPackages:
    rolldown: latest => 1.0.1
```

### Any additional comments?

This seemed to be working with 1.0.0.
Found at https://github.com/sapphi-red/zarara/issues/25#issuecomment-4456923248

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
The bug is fixed by #9514, so this PR only adds the regression test.

close #9401

The fixture exercises the dynamic-import + CJS-require shape from the issue: a static `assertNoStaticImportCycle` check against the dist graph plus a runtime `await import('./dist/entry-0.js')` smoke to catch the original `TypeError: __exportAll is not a function`.

**Why a regression test still matters.** Any optimization that moves or merges the runtime host has to anticipate the static imports that follow. There is no type or invariant enforcing this — it lives entirely in the head of whoever wrote each optimization pass. Forgetting it silently introduces a circular import, which is exactly the bug in #9401.

**Planned follow-up.** A subsequent PR will restructure this: split the runtime module into a standalone chunk during optimization, then merge it into an existing chunk as a final step *after* helper usages are attached. Optimization will then see a complete graph, and the kind of ad-hoc guarding #9514 added can be removed.

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#9419** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/9419?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#9418** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/9418?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/9418?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=9418).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shulaoda — APPROVED** [review]
