### PR TITLE
refactor: always split runtime module first

### LINKED ISSUE #9597: [Bug]: circular import generated when using dynamic import and require
### Reproduction link or steps

[REPL](https://repl.rolldown.rs/#eNqNkk1v2zAMhv8KodMGxI4/hrTzsGMw7LTDdpsHV7FpV50qpZLsJg3y36sPx3WKFAhgGCZFvnz4ygfSkuJAhGwwiesH7QNSzBILUtu443JD+Z97puOqovW+5qyuZG+2vana/uWlSuA7JN9KMUjWgMKnnin8VJJ46ZTy+EGX5LM9xt1WKqNjl5167AwkhVE9Hhd+cmrr5yQ+vhIktaLpCYQ9unETh98ogAxUgYdw9YejzYQoHijvcdQItHA4VboyMjJm7+0KiSspMzsh+8iuGeaZX6emE4KzdU7g4ysBcquVf2CTs3t06cKp3/OdiU7tzcR8MtFNODcxn0xUkvNGPou4lqJl3WyXCydhq+USfqBARQ02sNnDXU1VJ0H1AqItXFgTomjDBHRjU9WynekV2rR9NFqV2+wmS5Ms+7L6mmar9CZf3d5NzA22tOeWvRQATFjVInwDlASFUfsoKUlhg7OLcxXHhXvjzqASlBfw1zaMgev554+NQtT39D8W0FKu0Se3CjWqAddO/zfrBHXI2k2hnMvnyOkIzaQoiW8I+05k2ihWm/UO697Yol+qQTXXB3hkgrX7nyLgrMMvNi9x8OGa7D0N1nhuzdOGHF8BDZ9o+Q==)

### What is expected?

No error happens when executing `dist/entry-0.js`.

### What is actually happening?

The following error happens when executing `dist/entry-0.js`:
```
TypeError: __exportAll is not a function
```
In other words, the cyclic import "entry-0 -> node0 -> entry-0" is not output.

### System Info

```Shell
REPL 1.0.3
```

### Any additional comments?

This seemed to be working with 1.0.0.
Found at https://github.com/sapphi-red/zarara/issues/25#issuecomment-4560201943

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary

Reworks runtime-module chunk placement (see `meta/design/code-splitting.md` →
"Runtime Module Placement"): the runtime module is always extracted into its own
chunk first, then merged back into a proven-safe host chunk (the sole runtime
consumer / a chunk with the same reachability bitset / a consumer-set dominator),
guarded by TLA- and static-cycle checks. The initial layout is cycle-safe by
construction instead of place-by-bitset-then-peel-on-cycle.

A follow-up commit fixes a regression this surfaced: single-file `output.file`
(es/cjs) builds that pull in a runtime helper (e.g. a reified namespace) were
wrongly rejected with `[INVALID_OPTION] InvalidOutputFile`. The multi-chunk guard
in `generate()` counted the merged-away runtime chunk's tombstone (still in
`chunk_table`, but skipped at render time). It now counts only live chunks,
mirroring the render-time filter.

## Why some Rollup alignment tests are skipped

Three `chunking-form` samples are added to
`packages/rollup-tests/src/failed-tests.json`. **These are not workarounds for a
bug** — Rolldown's output is behaviorally correct; it just emits one fewer chunk
than Rollup.

The `chunking-form` suite only asserts that Rolldown emits the **same number of
chunks** as Rollup (`assert.strictEqual(actualChunkCount, expectedChunkCount)`);
it does not compare chunk contents. With the runtime now folded into a
same-bitset host chunk, these multi-entry topologies no longer need a standalone
runtime chunk, so Rolldown emits one fewer chunk than Rollup: Rollup hoists shared
content into a `generated-*.js` chunk, while Rolldown folds that content (plus the
runtime) into an existing entry chunk.

Each was verified by **executing** both Rolldown's `_actual/` and Rollup's
`_expected/` output and comparing observable behavior — entry exports, console
output, and computed values all match. The only differences are the chunk count
and cosmetic representation (Rolldown's namespace objects carry the
spec-compliant `Symbol.toStringTag: "Module"`, which Rollup's frozen-object
namespaces omit).

Affected samples (both `generates es` and `generates cjs`):

- `entry-point-without-own-code` — Handles entry points that contain no own code except imports and exports
- `namespace-object-import` — namespace object import
- `namespace-reexports` — namespace rendering with reexports

To re-check one, run the sample and diff its `_actual/` against `_expected/`, e.g.
`pnpm --filter rollup-tests test --grep "namespace-object-import: namespace object import"`.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

closed #9597

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#9419** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/9419?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/9419?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#9418** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/9418?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=9419).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shulaoda — APPROVED** [review]

File: meta/design/code-splitting.md [hunk 1]
```diff
@@ -158,58 +160,46 @@ Dynamic/emitted entries can become empty facades when all their modules are pull
...
-                ∪ ({original_host} if original_host is not marked Removed)
+                ∪ chunks whose included statements reference runtime-owned symbols
+                ∪ chunks containing modules that depend on the runtime module
+                ∪ chunks containing wrapped modules or side-effectful runtime dependencies
+                ∪ facade-elimination consumers added during the current pass
 ```
 
-The first term picks up chunks that already required helpers from the linking stage; the second term picks up chunks that facade elimination just announced; the third term re-adds the original host — the merge phase placed the runtime there because its bitset required it, making it an implicit consumer. The "not Removed" gate is defensive: `apply_common_chunk_merges` already retargets `module_to_chunk` when a host is merged into another chunk, so in practice `original_host` resolves to a still-live chunk. Deduplication is automatic via `FxHashSet`.
+Facade elimination can introduce the first runtime-helper consumer after early chunking. In that case it restores inclusion metadata, materializes the standalone runtime chunk, and then runs the same merge check.
```
Comment (h-a-n-a) [inline meta/design/code-splitting.md]: > Facade elimination can introduce the first runtime-helper consumer after early chunking.

Just out of my curiosity, would you please clarify the cases that you're referring here? 

Overall it looks good to me.

**Review by h-a-n-a — APPROVED** [review]

**Comment by hyfdev** [comment]
Reviewed this PR — the standalone-first runtime placement is a good direction and the cycle/TLA reasoning holds up. I found **one confirmed correctness regression** (verified with a live A/B run) and **two lower-priority items** (reasoned from the code, but **not** rigorously verified). Details below.

---

## 🔴 Confirmed (verified): runtime merge ignores `preserveEntrySignatures` and leaks helper exports onto an entry chunk

`try_merge_runtime_chunk` can fold the runtime module into a **user-defined entry chunk** without consulting `preserveEntrySignatures`. When another chunk reads a helper from that entry cross-chunk, the helper symbols (`__esmMin`, `__toESM`, …) — plus internal symbols like `init_lib` — get published onto the entry's **public export surface**, changing its signature.

The facade / common-chunk merge path guards exactly this via `can_merge_without_changing_entry_signature` (`chunk_optimizer.rs:816-818`), but the runtime merge path has no such guard. Note also that `find_single_runtime_bitset_host` (`chunk_optimizer.rs:1246-1272`) does **not** require `ChunkKind::Common`, so it can select a user entry as the host; and `runtime_merge_target_is_allowed` (`1289-1294`) only rejects `ManualCodeSplitting`.

### Minimal reproduction (verified)

Drop this in as `crates/rolldown/tests/rolldown/issues/repro_sig/` and run
`cargo test -p rolldown --test integration repro_sig -- --ignored`:

**`_config.json`**
```json
{
  "config": {
    "input": [
      { "name": "main", "import": "./main.js" },
      { "name": "lib", "import": "./lib.js" }
    ],
    "format": "cjs",
    "exports": "named",
    "strictExecutionOrder": true,
    "preserveEntrySignatures": "strict",
    "minifyInternalExports": false
  }
}
```

**`lib.js`** (entry — declared signature is `{ foo, bar }`)
```js
export const foo = 'foo_value';
export const bar = 42;
```

**`main.js`** (second entry — imports lib's exports and independently pulls runtime helpers)
```js
import assert from 'node:assert';
import { foo, bar } from './lib.js';
assert.strictEqual(foo, 'foo_value');
assert.strictEqual(bar, 42);
export { foo, bar };
```

> Equivalent JS-API options: `input: { main, lib }`, `output: { format: 'cjs', exports: 'named', preserveEntrySignatures: 'strict', minifyInternalExports: false }` (+ `experimental.strictExecutionOrder`).

### Observed result (A/B), with explicit `preserveEntrySignatures: "strict"`

I ran the identical fixture on this PR's HEAD (`24361d4b`) and on pre-PR `main` (`645ed627`):

**pre-PR `main` — `lib.js` exports exactly its declared signature ✅** (runtime/helpers/`init_lib` are isolated in a separate `lib2.js` chunk):
```js
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const require_lib = require("./lib2.js");
require_lib.init_lib();
exports.bar = require_lib.bar;
exports.foo = require_lib.foo;
```

**This PR — runtime merged into the strict entry; helpers + `init_lib` leak onto `lib.js` ❌:**
```js
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
// HIDDEN [\0rolldown/runtime.js]
//#region lib.js
var foo, bar;
var init_lib = __esmMin((() => { foo = "foo_value"; bar = 42; }));
//#endregion
init_lib();
exports.__esmMin = __esmMin;   // ← leaked
exports.__toESM = __toESM;     // ← leaked
exports.bar = bar;
exports.foo = foo;
Object.defineProperty(exports, "init_lib", { enumerable: true, get: () => init_lib }); // ← leaked
```

### Why this matters beyond opt-in `strict`

This also reproduces under the **default** `preserveEntrySignatures: "exports-only"`, which is *strict for entries that have exports* — and it's already visible in this PR's own committed snapshots, e.g. `topics/exports/entry_esm_named_named/artifacts.snap` and `entry_esm_named_default/artifacts.snap`, where the `lib` entry gained `__esmMin`/`__toESM`/`init_lib` exports vs `main`. So default-config multi-entry builds with CJS interop / reified namespaces are affected, not just explicit `strict`.

### Suggested fix

Add a signature guard to the runtime merge target selection: reject a candidate that is a user entry with `preserve_entry_signature != AllowExtension` **when the merge would re-export helpers** (i.e. more than one runtime consumer). Equivalently, only allow merging the runtime into such an entry when it is the **sole** runtime consumer (helpers stay internal, which is already the safe single-consumer case). `Chunk.preserve_entry_signature` already exists, so the guard is cheap. (Worth also checking whether the facade-elimination interaction that pulls the lib *body* into the entry should respect the same guard.)

---

## 🟡 Two lower-priority items (NOT rigorously verified — reasoned from the code only)

**1. Perf: the runtime-symbol scan now runs unconditionally and largely redundantly.** `try_merge_runtime_chunk(None)` is now called on every code-split build (`code_splitting.rs:970`), and in `collect_runtime_consumer_chunks` the `||` chain evaluates the expensive `chunk_references_runtime_symbol` (per-symbol `canonical_ref_resolving_namespace` scan, `chunk_optimizer.rs:1333-1363`) **before** the cheaper `dependencies.contains(&runtime_module_idx)` (`1318`). Since `patch_module_dependencies` already populates `dependencies` with the runtime owner for these same referenced symbols, the scan looks redundant on this path. Likely a cheap win to reorder those `||` operands (or gate the scan). I have **not** benchmarked this, and the existing CodSpeed presets are all single-entry so they don't exercise it — would be good to add a multi-entry/dynamic-import bench.

**2. Test coverage: 3 `chunking-form` Rollup samples moved from passing → skipped.** `entry-point-without-own-code`, `namespace-object-import`, `namespace-reexports` (×cjs/es, `failed-tests.json`; `passed 1213→1207`). The chunking-form suite only asserts chunk **count**, not contents, so a "one fewer chunk" delta gets skipped rather than characterized. The PR's explanation (runtime folded into a same-bitset host → one fewer chunk, behavior unchanged) is plausible and consistent with the code (the merge only ever removes the runtime chunk, never merges two user chunks), but I did **not** independently diff the actual `_actual/` vs `_expected/` output for these three. A content-aware rolldown-side fixture pinning the intended topology would make the "benign" claim durable.

(Also minor: the design-doc "Regression coverage" list omits `issues/9597`, the headline new fixture this PR adds.)

**Review by hyf0 — APPROVED** [review]
LGTM. Please take a look at the high risk issue mentioned in https://github.com/rolldown/rolldown/pull/9419#issuecomment-4619837715

**Comment by IWANABETHATGUY** [comment]
> Reviewed this PR — the standalone-first runtime placement is a good direction and the cycle/TLA reasoning holds up. I found **one confirmed correctness regression** (verified with a live A/B run) and **two lower-priority items** (reasoned from the code, but **not** rigorously verified). Details below.
> 
> ## 🔴 Confirmed (verified): runtime merge ignores `preserveEntrySignatures` and leaks helper exports onto an entry chunk
> `try_merge_runtime_chunk` can fold the runtime module into a **user-defined entry chunk** without consulting `preserveEntrySignatures`. When another chunk reads a helper from that entry cross-chunk, the helper symbols (`__esmMin`, `__toESM`, …) — plus internal symbols like `init_lib` — get published onto the entry's **public export surface**, changing its signature.
> 
> The facade / common-chunk merge path guards exactly this via `can_merge_without_changing_entry_signature` (`chunk_optimizer.rs:816-818`), but the runtime merge path has no such guard. Note also that `find_single_runtime_bitset_host` (`chunk_optimizer.rs:1246-1272`) does **not** require `ChunkKind::Common`, so it can select a user entry as the host; and `runtime_merge_target_is_allowed` (`1289-1294`) only rejects `ManualCodeSplitting`.
> 
> ### Minimal reproduction (verified)
> Drop this in as `crates/rolldown/tests/rolldown/issues/repro_sig/` and run `cargo test -p rolldown --test integration repro_sig -- --ignored`:
> 
> **`_config.json`**
> 
> ```json
> {
>   "config": {
>     "input": [
>       { "name": "main", "import": "./main.js" },
>       { "name": "lib", "import": "./lib.js" }
>     ],
>     "format": "cjs",
>     "exports": "named",
>     "strictExecutionOrder": true,
>     "preserveEntrySignatures": "strict",
>     "minifyInternalExports": false
>   }
> }
> ```
> 
> **`lib.js`** (entry — declared signature is `{ foo, bar }`)
> 
> ```js
> export const foo = 'foo_value';
> export const bar = 42;
> ```
> 
> **`main.js`** (second entry — imports lib's exports and independently pulls runtime helpers)
> 
> ```js
> import assert from 'node:assert';
> import { foo, bar } from './lib.js';
> assert.strictEqual(foo, 'foo_value');
> assert.strictEqual(bar, 42);
> export { foo, bar };
> ```
> 
> > Equivalent JS-API options: `input: { main, lib }`, `output: { format: 'cjs', exports: 'named', preserveEntrySignatures: 'strict', minifyInternalExports: false }` (+ `experimental.strictExecutionOrder`).
> 
> ### Observed result (A/B), with explicit `preserveEntrySignatures: "strict"`
> I ran the identical fixture on this PR's HEAD (`24361d4b`) and on pre-PR `main` (`645ed627`):
> 
> **pre-PR `main` — `lib.js` exports exactly its declared signature ✅** (runtime/helpers/`init_lib` are isolated in a separate `lib2.js` chunk):
> 
> ```js
> Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
> const require_lib = require("./lib2.js");
> require_lib.init_lib();
> exports.bar = require_lib.bar;
> exports.foo = require_lib.foo;
> ```
> 
> **This PR — runtime merged into the strict entry; helpers + `init_lib` leak onto `lib.js` ❌:**
> 
> ```js
> Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
> // HIDDEN [\0rolldown/runtime.js]
> //#region lib.js
> var foo, bar;
> var init_lib = __esmMin((() => { foo = "foo_value"; bar = 42; }));
> //#endregion
> init_lib();
> exports.__esmMin = __esmMin;   // ← leaked
> exports.__toESM = __toESM;     // ← leaked
> exports.bar = bar;
> exports.foo = foo;
> Object.defineProperty(exports, "init_lib", { enumerable: true, get: () => init_lib }); // ← leaked
> ```
> 
> ### Why this matters beyond opt-in `strict`
> This also reproduces under the **default** `preserveEntrySignatures: "exports-only"`, which is _strict for entries that have exports_ — and it's already visible in this PR's own committed snapshots, e.g. `topics/exports/entry_esm_named_named/artifacts.snap` and `entry_esm_named_default/artifacts.snap`, where the `lib` entry gained `__esmMin`/`__toESM`/`init_lib` exports vs `main`. So default-config multi-entry builds with CJS interop / reified namespaces are affected, not just explicit `strict`.
> 
> ### Suggested fix
> Add a signature guard to the runtime merge target selection: reject a candidate that is a user entry with `preserve_entry_signature != AllowExtension` **when the merge would re-export helpers** (i.e. more than one runtime consumer). Equivalently, only allow merging the runtime into such an entry when it is the **sole** runtime consumer (helpers stay internal, which is already the safe single-consumer case). `Chunk.preserve_entry_signature` already exists, so the guard is cheap. (Worth also checking whether the facade-elimination interaction that pulls the lib _body_ into the entry should respect the same guard.)
> 
> ## 🟡 Two lower-priority items (NOT rigorously verified — reasoned from the code only)
> **1. Perf: the runtime-symbol scan now runs unconditionally and largely redundantly.** `try_merge_runtime_chunk(None)` is now called on every code-split build (`code_splitting.rs:970`), and in `collect_runtime_consumer_chunks` the `||` chain evaluates the expensive `chunk_references_runtime_symbol` (per-symbol `canonical_ref_resolving_namespace` scan, `chunk_optimizer.rs:1333-1363`) **before** the cheaper `dependencies.contains(&runtime_module_idx)` (`1318`). Since `patch_module_dependencies` already populates `dependencies` with the runtime owner for these same referenced symbols, the scan looks redundant on this path. Likely a cheap win to reorder those `||` operands (or gate the scan). I have **not** benchmarked this, and the existing CodSpeed presets are all single-entry so they don't exercise it — would be good to add a multi-entry/dynamic-import bench.
> 
> **2. Test coverage: 3 `chunking-form` Rollup samples moved from passing → skipped.** `entry-point-without-own-code`, `namespace-object-import`, `namespace-reexports` (×cjs/es, `failed-tests.json`; `passed 1213→1207`). The chunking-form suite only asserts chunk **count**, not contents, so a "one fewer chunk" delta gets skipped rather than characterized. The PR's explanation (runtime folded into a same-bitset host → one fewer chunk, behavior unchanged) is plausible and consistent with the code (the merge only ever removes the runtime chunk, never merges two user chunks), but I did **not** independently diff the actual `_actual/` vs `_expected/` output for these three. A content-aware rolldown-side fixture pinning the intended topology would make the "benign" claim durable.
> 
> (Also minor: the design-doc "Regression coverage" list omits `issues/9597`, the headline new fixture this PR adds.)

addressed

**Comment by IWANABETHATGUY** [comment]
### Merge activity

* **Jun 4, 8:20 AM UTC**: The merge label 'graphite: merge-when-ready' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown) once it meets the requirements.
* **Jun 4, 8:22 AM UTC**: `IWANABETHATGUY` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
* **Jun 4, 8:27 AM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).

**Comment by sapphi-red** [comment]
@IWANABETHATGUY Would you run https://github.com/sapphi-red/zarara with the changes to ensure there's no regression? (if you haven't)

**Comment by IWANABETHATGUY** [comment]
> @IWANABETHATGUY Would you run https://github.com/sapphi-red/zarara with the changes to ensure there's no regression? (if you haven't)

I have run it twice locally, each time with 6000 seeds. Not sure if it is enough.

**Comment by sapphi-red** [comment]
Ah, ok. That should be sufficient.
