### PR TITLE
perf: remove unnecessary assignment for default export

### LINKED ISSUE #4013: [Feature Request]: Remove unnecessary assign for default export
### Reproduction link or steps

https://esbuild.github.io/try/#YgAwLjI1LjIALS1idW5kbGUgLS1mb3JtYXQ9ZXNtAGUAZW50cnkuanMAdmFyIHggPSA0MgovL3ggPSA0MQoKZXhwb3J0IGRlZmF1bHQgeAoKLy94ID0gNDA

`entry_default` is not necessary in this case.

### What is expected?

Like Rollup, assign if needed.

https://rollupjs.org/repl/?version=4.39.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMnZhciUyMHglMjAlM0QlMjA0MiU1Q24lMkYlMkYlMjB4JTIwJTNEJTIwNDElNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjB4JTVDbiU1Q24lMkYlMkYlMjB4JTIwJTNEJTIwNDAlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiU3RCU3RA==

### What is actually happening?

Always assigned to a new variable like esbuild
https://esbuild.github.io/try/#YgAwLjI1LjIALS1idW5kbGUgLS1mb3JtYXQ9ZXNtAGUAZW50cnkuanMAdmFyIHggPSA0MgovL3ggPSA0MQoKZXhwb3J0IGRlZmF1bHQgeAoKLy94ID0gNDA

### System Info

```Shell
N/A
```

### Any additional comments?

~~https://github.com/sxzz/rolldown-plugin-dts needs this behavior.~~ No longer needed.

### LINKED ISSUE #5847: [Bug]: Compromise library not working in development anymore
### Reproduction link or steps

https://stackblitz.com/edit/github-z3jerszh-yzc4e3uh?file=package.json,src%2Fmain.ts

### What is expected?

Development should work like production. Regressed fairly recently. Broken in 7.1.2, worked in 7.0.12

### What is actually happening?

It crashes in development, maybe due to some local scope issues?

```
Uncaught TypeError: nlp$1.addTags is not a function
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by shulaoda**
closes #4013, partially revert of #5856, and fixed issue #5847.

### CODE REVIEW

**Comment by shulaoda** [comment]
* **#8127** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8127?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8127?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=8127).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by sapphi-red** [comment]
> reopen issue #5847

Does this mean this PR will introduce a bug temporarily?

**Comment by shulaoda** [comment]
> > reopen issue #5847
> 
> Does this mean this PR will introduce a bug temporarily?

No, this has been fixed. I added the relevant test cases, but we no longer support the `import .. from '..'; export default ..` form. Imported symbols must be assigned to a local binding variable (See https://github.com/rolldown/rolldown/pull/8128#discussion_r2744385647). I updated the description.

**Comment by sapphi-red** [comment]
What do you mean by "no longer support"?

**Comment by shulaoda** [comment]
> What do you mean by "no longer support"?

Previously, #5856 supported the `import a from '..'; export default a` pattern without creating an intermediate local binding for `a`. However, this causes an issue: Rolldown’s tree-shaking and lazy barrel logic determine whether to load all import records based on whether a symbol is a local binding.

Rolldown distinguishes `export default a` by generating a local binding symbol, as discussed in https://github.com/rolldown/rolldown/pull/8128#discussion_r2744385647.

**Comment by shulaoda** [comment]
> "no longer support"

~~So this means that creating an intermediate variable for `import a from '..'; export default a` is necessary. By `"no longer support"` I mean that I now understand the behavior correctly and believe this pattern should not be supported.~~

Supporting this pattern may be feasible, but it would likely require changes in the link stage. It might be a bit complex.

File: crates/rolldown/tests/rolldown/misc/invalid_ident_repr/artifacts.snap [hunk 1]
```diff
@@ -10,9 +10,8 @@ import assert from "node:assert";
 
 // HIDDEN [\0rolldown/runtime.js]
 //#region 1aaa.js
-var _1aaa_exports = /* @__PURE__ */ __exportAll({ default: () => _1aaa_default });
+var _1aaa_exports = /* @__PURE__ */ __exportAll({ default: () => a });
 const a = "shared.js";
-var _1aaa_default = a;
```
Comment (sapphi-red) [inline crates/rolldown/tests/rolldown/misc/invalid_ident_repr/artifacts.snap:15]: It seems this test tries to test the `_1aaa_default` name. So I think we should tweak the test case to preserve the name.

File: crates/rolldown/tests/rolldown/topics/live_bindings/default_export_expr/artifacts.snap [hunk 2]
```diff
@@ -7,15 +7,15 @@ source: crates/rolldown_testing/src/integration_test.rs
...
 function reset() {
-	count = 0;
+	count$1 = 0;
 }
 function inc() {
-	count += 1;
+	count$1 += 1;
 }
-var main_default = count;
+var count = count$1;
```
Comment (sapphi-red) [inline crates/rolldown/tests/rolldown/topics/live_bindings/default_export_expr/artifacts.snap]: The previous variable name is easier to understand to me. Not necessary, but it would be nice to keep the name.

**Comment by sapphi-red** [comment]
I see 👍

File: crates/rolldown/src/ast_scanner/mod.rs [hunk 3]
```diff
@@ -798,7 +798,37 @@ impl<'me, 'ast: 'me> AstScanner<'me, 'ast> {
...
+          // 3. Symbol has no write references (not: `let foo = 1; foo = 2; export default foo;`)
+          // See https://github.com/rollup/rollup/blob/061a0387/test/function/samples/default-export-before-declaration
+          if (id.span.is_unspanned()
+            || symbol_id_span.is_unspanned()
+            || symbol_id_span.start > id.span.start)
+            || self
+              .result
+              .named_imports
+              .contains_key(&SymbolRef::from((self.immutable_ctx.idx, symbol_id)))
+            || scoping.get_resolved_references(symbol_id).any(Reference::is_write)
```
Comment (sapphi-red) [inline crates/rolldown/src/ast_scanner/mod.rs]: I guess we need to check for redeclarations.
```js
var a = 1;
var a = 2;
```
```js
var a = 1;
function a () {}
```
IIRC these are not included in resolved references.

File: crates/rolldown/src/ast_scanner/mod.rs [hunk 4]
```diff
@@ -798,7 +798,37 @@ impl<'me, 'ast: 'me> AstScanner<'me, 'ast> {
...
+          {
+            // TODO: Maybe we shouldn't rewrite the symbol name here to avoid rename conflicts later?
```
Comment (sapphi-red) [inline crates/rolldown/src/ast_scanner/mod.rs]: I'm not sure about this TODO comment, so I'll leave this to others.

Comment (shulaoda) [reply crates/rolldown/src/ast_scanner/mod.rs]: It's about https://github.com/rolldown/rolldown/pull/8127#discussion_r2744486210

File: crates/rolldown/tests/rolldown/issues/5847/_config.json [hunk 5]
```diff
@@ -0,0 +1,6 @@
+{
+  "config": {
+    "external": ["@meojs/cfgs/package.json", "foo"]
```
Comment (IWANABETHATGUY) [inline crates/rolldown/tests/rolldown/issues/5847/_config.json]: The external seems unused. And we should enable the `expectExecuted`

File: crates/rolldown/tests/rolldown/misc/invalid_ident_repr/artifacts.snap (hunk 1 above)
Comment (shulaoda) [reply crates/rolldown/tests/rolldown/misc/invalid_ident_repr/artifacts.snap:15]: I traced it back and found that it’s meant to test whether `1aaa_exports` is legitimized into a valid identifier. The current `var _1aaa_exports = ..` is the correct behavior and it does not change the intent of the test..

File: crates/rolldown/tests/rolldown/issues/5847/artifacts.snap [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+//#endregion
+export { compromise_default as default };
+```
+
+## main.js
+
+```js
+//#region main.js
+async function cc() {
+	console.log((await import("./compromise.js")).default);
```
Comment (IWANABETHATGUY) [inline crates/rolldown/tests/rolldown/issues/5847/artifacts.snap]: Use `assert` if possible.

File: crates/rolldown/tests/rolldown/issues/5847/_config.json (hunk 5 above)
Comment (shulaoda) [reply crates/rolldown/tests/rolldown/issues/5847/_config.json]: Ah, I forgot about it when I copied it. 👍

File: crates/rolldown/tests/rolldown/misc/invalid_ident_repr/artifacts.snap (hunk 1 above)
Comment (sapphi-red) [reply crates/rolldown/tests/rolldown/misc/invalid_ident_repr/artifacts.snap:15]: Ah, I overlooked the `_1aaa_exports` variable name. Make sense.

File: crates/rolldown/src/ast_scanner/mod.rs (hunk 3 above)
Comment (shulaoda) [reply crates/rolldown/src/ast_scanner/mod.rs]: Done.

**Review by sapphi-red — APPROVED** [review]

**Comment by hyf0** [comment]
well done!

**Review by IWANABETHATGUY — APPROVED** [review]

**Comment by shulaoda** [comment]
### Merge activity

* **Jan 30, 5:08 AM UTC**: The merge label 'graphite: merge-when-ready' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown) once it meets the requirements.
* **Jan 30, 5:08 AM UTC**: `shulaoda` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
* **Jan 30, 5:18 AM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
