### PR TITLE
fix: Inlining dynamic imports broken with multiple entry points

### LINKED ISSUE #8027: [Bug]: Inlining dynamic imports broken with multiple entry points (beta.59 regression)
### Reproduction link or steps

https://repl.rolldown.rs/#eNptj81uhCAUhV/lhg2aWDqzdTJ9hSZNd6ULo1hp9GIA+xPCuxdE7ExmEhbcn/Odcx3pSe2IVuPYqW9krcJefjBrYhdJfW9SkTYM5DQrbcH+zgIcvGxrz7OVCg146LWagGY55cgxIIyFBKpvJGdwHAEkzout4Y1OjUT2aWhFlR2Ejt/3iqOPJPGzmneib5YxIzkSX5G8nA/Y66vYnLBHMzRadGHEySkq9zpL/xtJu7n2C7Yx8vopyhQbQAu7aAT6OkgD4TWQ9Ps+Pa3po9V2WzbK5WXEgl4kpCULZ2BRuJUGvoTzUzZOMSK8DHcE+leAHNmBHR50y47E/wF/s6Ha

### What is expected?

The dynamic import works as expected.

### What is actually happening?

The dynamic import imports a module that doesn't have any exports after bundling.

```js
dist/main.js:3
	func();
	^

TypeError: func is not a function
    at dist/main.js:3:2
```

### System Info

```Shell
rolldown: 1.0.0-rc.1
```

### Any additional comments?

I suspect this is caused by #7742

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed #8027

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#8047** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8047?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#8046** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8046?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#8037** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8037?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8037?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=8037).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/tests/rolldown/tree_shaking/issue_4682/artifacts.snap [hunk 1]
```diff
@@ -23,19 +23,28 @@ export { lazyLoad };
...
-//#endregion
 //#region main.js
 import("./dynamic.js").then(async ({ lazyLoad }) => {
 	await lazyLoad();
 });
 
 //#endregion
 ```
+
+## static.js
```
Comment (IWANABETHATGUY) [inline crates/rolldown/tests/rolldown/tree_shaking/issue_4682/artifacts.snap:36]: The regression will be fixed in next pr.

**Review by shulaoda — APPROVED** [review]
