### ISSUE TITLE
[Bug]: CJS subpath import in lazy chunk throws "X is not a function" — chunk-split interop mismatch (rolldown 1.0.0 / 1.0.1)

### ISSUE THREAD

**Issue by jj-regask** [rolldown/rolldown#9440]
> Filed by @thedoublejay after a production bisect.

### Reproduction link or steps

I don't have a runnable repro repo handy yet, but the failure is fully reproducible from a vanilla Vite 8 project meeting **all** of the following conditions, and I'm happy to build a standalone repo on request:

1. **Vite 8.0.12 or 8.0.13** (so rolldown `1.0.0` or `1.0.1`).
2. A `.jsx` (or any ESM) file that lives **inside a `React.lazy(() => import(...))` boundary** — i.e. ends up in a chunk that isn't the main entry bundle.
3. That file uses a **default CJS subpath import**, e.g.:

   ```js
   // Button.jsx — under React.lazy boundary
   import get from "lodash/get";
   import has from "lodash/has";
   ```

4. Run a production build (`vite build` with the default `output.format: "es"`) and load the built app in a browser. Navigate to the route that triggers the lazy boundary.

The browser throws at module init of the lazy chunk:

```
TypeError: c is not a function
    at app.<hash>.chunk.js:1:272
Caused by: React ErrorBoundary TypeError: c is not a function
    at Lazy (<anonymous>)
    at Suspense (<anonymous>)
```

The minified chunk emitted by rolldown looks like:

```js
// importing lazy chunk
import { vi as a } from "./main-bundle.js";        // a = _interopRequireDefault helper
import { T as c } from "./vendor.chunk.js";         // c = the lodash chunk's export
import { fi as n, q as i } from "./main-bundle.js"; // these wrappers work fine

var l = a(n()), u = a(i()), d = a(c());
//                              ^^^^^^ throws — c is the namespace value, not a __require() wrapper
```

`n()` and `i()` (CJS modules emitted into the **main bundle**) successfully return a namespace. `c()` (the same kind of CJS module emitted into a **separately chunk-split vendor chunk**) is exported as the namespace value, not as the `__require()` lazy-wrapper function. The importer side still tries to call it.

### What is expected?

When rolldown decides to put a CJS module into a separate output chunk, the import-site code and the export-side emission should agree on the interop shape:

- Either both sides treat the export as a `__require()` lazy-wrapper function, **or**
- both sides treat the export as a static namespace value.

Same behavior as `rolldown` `1.0.0-rc.18` and earlier (and the same as Rollup's behavior for the same input).

### What is actually happening?

In `rolldown` `1.0.0` and `1.0.1`, when a CJS module ends up in a separate output chunk (not the main bundle):

- The **import-site** emits `a(c())` — i.e. calls `c` as a `__require()` wrapper, then passes the result to `_interopRequireDefault`.
- The **export-side** emits the resolved module namespace directly as `T` (the bare object), not wrapped in a callable getter.

Result: `TypeError: c is not a function` thrown synchronously inside the lazy chunk's top-level code (before the first `export` evaluates), which surfaces as a `React.lazy` rejection caught by the nearest `ErrorBoundary`.

The same source code built with `rolldown` `1.0.0-rc.18` (shipped in Vite `8.0.11`) emits a consistent shape on both sides and runs correctly.

### System Info

```Shell
  System:
    OS: macOS 26.5
    CPU: arm64 Apple Silicon
  Binaries:
    Node: 24.14.1
    npm: 11.11.0
    Yarn: 4.13.0
  Browsers:
    Chrome: 148.0.7778.168
  npmPackages (broken configuration):
    vite: 8.0.13
    rolldown: 1.0.1 (transitive, via vite)
    @vitejs/plugin-react: 6.0.2
```

Reproduced on macOS arm64. Reproduces with both `lodash@4.17.23` and `lodash@4.18.1` (so the CJS package itself isn't the variable).

### Bisect — which Vite/rolldown versions are affected?

| Vite version | Bundled rolldown | Status |
|---|---|---|
| 8.0.1  | `1.0.0-rc.10` | ✅ works |
| 8.0.11 | `1.0.0-rc.18` (Apr 29, 2026) | ✅ works |
| 8.0.12 | `1.0.0` (May 7, 2026, first stable) | ⚠️ very likely affected (same rolldown family as 8.0.13) — not directly retested locally |
| 8.0.13 | `1.0.1` (May 13, 2026) | ❌ reproduces |

Bisect was carried out against a real production app: same source code, same install state, only the Vite (and therefore rolldown) version changed.

Additionally ruled out as the cause:
- `lodash`/`lodash-es` version (`4.17.23` vs `4.18.1` — both reproduce with broken Vite, both work with Vite `8.0.11`)
- `@vitejs/plugin-react` version (`6.0.0` and `6.0.2` both reproduce with broken Vite)

### Any additional comments?

- Workaround in use: pin Vite to exact `8.0.11`.
- I'm filing here rather than at `vitejs/vite` because the bisect points directly at the bundled rolldown version — please reroute if more appropriate.
- I can put together a minimal standalone repository (vanilla Vite + React, one CJS subpath import, one `React.lazy` boundary) if it would help triage — happy to do that on request.
